### ISSUE TITLE
client.clearStore() or client.resetStore() do nothing

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-cache-persist#126]
Calling either `await client.clearStore()` or `await client.resetStore()` do nothing.

My `localstorage` persisted cache doesn't change. **Why?**

I think it should remove persisted cache in `localStorage`, isn't it?

_A bug?_

```json
    "apollo-cache-inmemory": "1.5.1",
    "apollo-cache-persist": "0.1.1",
    "apollo-client": "2.5.1",
    "apollo-link": "1.2.11",
    "apollo-link-context": "1.0.17",
    "apollo-link-error": "1.1.10",
    "apollo-link-http": "1.5.14",
```

**Comment by wtrocki** [comment]
What will be your Apollo Client version?
Apollo client changed a little for locastate stuff and the issue was there.
Your version of cache-persist did not change for 2 years.

https://github.com/apollographql/apollo-client/blob/58cb6d5437c00e42487052b727eb30190e31fbad/packages/apollo-client/src/core/QueryManager.ts#L913

**Comment by frederikhors** [comment]
I edited with all versions.

Anyway I think `clearStore()` is the same. Am I right?

**Comment by wtrocki** [comment]
After cleanup I see `{}` in the cache. Are some queries executed in that time that can like confuse cache persist?

**Comment by wtrocki** [comment]
I will do the demo setup online. You can use persistor from this repository to wipe cache in the mean time. See advanced use cases in doc

**Comment by frederikhors** [comment]
> After cleanup I see `{}` in the cache. Are some queries executed in that time that can like confuse cache persist? Trying to get if this is a somewhat timing issue.

Not at all.

Just one query to create cache correctly. Wait. Nothing. Wait again. Nothing because nothing has to happen. Logout click(), `await client.clearStore()`: nothing. Localstorage still there.

I'll try to create a codesandbox ASAP.

**Comment by frederikhors** [comment]
Edited previous one.

**Comment by wtrocki** [comment]
@frederikhors I have done example app to show how this can be done:
https://codesandbox.io/embed/basic-apollo-app-hiis7?codemirror=1

1) We need to clear actual cache 
2) We need to call persistor after to clear storage

If we do not wait we going to get these nasty timing issues where persistence will be cleared but it can still get hot InMemCache object.

**Comment by wtrocki** [comment]
I think that Client or cache will not know about cache-persist layer so if we want to make sure that is persisted we need to use both. The improvement here will be for persistor to actually clear the cache but this will be breaking change that may cause some problems in existing applications. Having another helper method is fine so I will be open for accepting contributions for that.

**Comment by wtrocki** [comment]
The idea to improve that is to hook into InMemory cache clear method and perform persistor clear. It will be little bit hacky and it will work for InMemoryCache but it will provide more seamless behavior that developers will expect.

**Please add +1 if you would like to have this in our Roadmap. **

**Comment by wtrocki** [comment]
Added to roadmap!

**Comment by seromenho** [comment]
I was doing this for example for `delete` on `cache.data`. Very similar to what trigger `write` is. 
I was passing custom trigger function, the one from [onCacheWrite](https://github.com/apollographql/apollo-cache-persist/blob/master/src/onCacheWrite.ts) by also add 
```js
const dataDelete = cache.data.delete;
cache.data.delete = (...args: any[]) => {
  dataDelete.apply(cache, args);
  persist();
};
return () => {
    cache.write = write;
    cache.data.delete = dataDelete;
};
```

Would it be interesting to have also `cache.data.delete`?
Or maybe it's just easier and less intrusive the user to just persist itself after the operation?
I've seen this was added to the backlog, if there's some list of actions that we are expecting write to persist I can help and submit a PR.

**Comment by wtrocki** [comment]
I think we simply need to hook to cache.clear method and call persistor.purge. This simple fix is going to resolve issue. Any contribution welcome as I would need to review it and approve it

**Comment by johnnyoshika** [comment]
> I think we simply need to hook to cache.clear method and call persistor.purge. This simple fix is going to resolve issue. Any contribution welcome as I would need to review it and approve it

A quick check-in. Any update on this?

**Comment by wtrocki** [comment]
@johnnyoshika We have documentation and sandbox above. Apollo 3.x is changing the cache layer - both loads and flushing so I'm going to look into more comprehensive handlers once that is official relasesed

**Comment by johnnyoshika** [comment]
@wtrocki Thanks!

So for now it looks like I need to manually call `persistor.purge()` after `clearStore()`. I need to do the purge deep inside my Logout component in React. The Logout.js example below seems to work but is there any downside?

### src/index.js
```
const cache = new InMemoryCache();
const waitOnCache = persistCache({
  cache,
  storage: window.localStorage,
});
const client = new ApolloClient({
  cache,
});
waitOnCache.then(() => {
  ReactDOM.render(
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>,
    document.getElementById('root'),
  );
});
```

### Logout.js
```
import React from 'react';
import { useApolloClient } from '@apollo/react-hooks';
import { CachePersistor } from 'apollo-cache-persist';

const Logout = () => {
  const client = useApolloClient();
  const persistor = new CachePersistor({
    cache: client.cache,
    storage: window.localStorage,
  });

  const handleClick = e => {
    e.preventDefault();
    client.clearStore().then(() => {
      persistor.purge().then(
        () => {
          // continue...
        }
      );
    });
  };

  return (
    <a href="/" onClick={handleClick}>
      Log out
    </a>
  );
};

export default Logout;

```

**Comment by wtrocki** [comment]
> The Logout.js example below seems to work but is there any downside?

No problem with that. The fix that we talking about was to just wrap both into a single method so actual behavior should be the same. 

So general snippet for logout should look like this
```
await client.clearStore()
await persistor.purge()
history.push('/');
```

**Comment by grinono** [comment]
Saw the same issue on with the persistor. Even AsyncStorage.clear() did not clear the persistor cache somehow

**Comment by wtrocki** [comment]
> Even AsyncStorage.clear() did not clear the persistor cache somehow

It happens when clearStore is not awaited.
Proper handler:
```
await client.destroy()
await client.clearStore()
await persistor.purge()
```
Can cause issues:
```
client.clearStore()
persistor.purge()
```

**Comment by ryananthonydiaz** [comment]
> @frederikhors I have done example app to show how this can be done:
> https://codesandbox.io/embed/basic-apollo-app-hiis7?codemirror=1
> 
> 1. We need to clear actual cache
> 2. We need to call persistor after to clear storage
> 
> If we do not wait we going to get these nasty timing issues where persistence will be cleared but it can still get hot InMemCache object.

That code SandBox helped me greatly - thank you.

**Comment by wtrocki** [comment]
We have covered this case in example apps and readme
