### ISSUE TITLE
Bundle with Rollup

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-cache-persist#144]
Using Rollup for bundling I'm getting this error:

```log
src/main.js → public/bundle.js...

[!] Error: 'persistCache' is not exported by node_modules\apollo-cache-persist\bundle.umd.js

https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src\apollo.js (6:9)

6: import { persistCache } from 'apollo-cache-persist'
```

I can fix it using:

```js
commonjs({
  namedExports: {
    'node_modules/apollo-cache-persist/bundle.umd.js': ['persistCache']
  }
})
```

But maybe we can fix it better exporting esm?

Please note I'm using also this in `rollup.config.js`:

```js
resolve({ browser: true }),
```

because of this: https://github.com/apollographql/subscriptions-transport-ws/issues/563#issuecomment-495219432

**Comment by frederikhors** [comment]
Updated.

**Comment by wtrocki** [comment]
@frederikhors Perfect. Yes that is going to be done soon - hoping to get some changes and get to release package.
