### ISSUE TITLE
Parse persisted cache or parse data before storing in cache

### ISSUE THREAD

**Issue by mptorz** [apollographql/apollo-cache-persist#176]
Hello,

Currently, one of our Apollo links parses all the data to convert dates into Moment objects and all IDs to numbers like that:

`const parse = new ApolloLink((operation, forward) => {
  return forward!(operation).map((response) => {
    return parseIdAndTimeStrings(response)
  })
})`

The problem we have is that when we use the cache it serializes data before this data is parsed, so when our app will use cache to retrieve some data it will get it as strings (instead of moment objects). 

What we want to achieve is to either:
* parse the data before it hits the cache
* parse the data after it is restored from the cache

Whatever is easier and better. I had a very hard time approaching this problem and I could not find any helpful resources so I decided to create a new issue.

**Comment by wtrocki** [comment]
The store is just a mirror for the InMemory. 
I think this should work as cache is updated after all links are done however we use wrong method here. `map`will be an method that is executed after cache. When using regular link forward.subscribe then you can mutate object and it will land in cache (and persistence layer) in the right shape. 

I woul suggest to post this in spectrum as well as this is faily common use case I have seen many times.

**Comment by wtrocki** [comment]
Anyway. I do not think that this is the right repository for this issue (although the problem is store related) so going to close. If that do not work let me know - we can reopen this issue.

**Comment by mptorz** [comment]
I tried using forward.subscribe and mutate the object, but it still gets cached unparsed:
`const parse = new ApolloLink((operation, forward) => {
  return new Observable((observer) => {
    let sub: any

    try {
      sub = forward!(operation).subscribe({
        next: (result) => {
          const mapped = parseIdAndTimeStrings(result)
          result.data = mapped.data
          observer.next(result)
        },
        error: (error) => {
          console.error(error)
        },
        complete: observer.complete.bind(observer),
      })
    } catch (e) {
      observer.error(e)
    }
    return () => {
      if (sub) sub.unsubscribe()
    }
  })
})`

I am not sure why that is the case

**Comment by wtrocki** [comment]
Thank you for sharing the repository I will take look.

**Comment by mptorz** [comment]
Just fyi that is not actually my repo and I didn't even use the module. I just copied some code hoping that it would work well with the cache. But neither my original approach nor the one I copied from that repo seem to be working so far. No matter what I do it doesn't work.

**Comment by mptorz** [comment]
> I would recommend creating a separate link. I do modify data in links very often and it works/

Would you be able to share any example? When I modify the data in the link it only works with network requests :/

**Comment by wtrocki** [comment]
Ah.. now I get you. Yes HTTP link needs to be involved. When getting stuff from cache the flow is different. I would recomend to log issue on apollo client.
