### ISSUE TITLE
redux-persist-expo-filesystem not working without @ts-ignore.

### ISSUE THREAD

**Issue by GollyJer** [apollographql/apollo-cache-persist#211]
I'm trying to use the **redux-persist-expo-filesystem** found in the [Storage Engines](https://github.com/rt2zz/redux-persist#storage-engines) list for redux-persist.

**redux-persist-expo-filesystem**  works when passing to the storage param of **redux-persist**
but **apollo-cache-persist** chokes on the type.

My assumption from the docs is they would behave the same for all storage providers.

Here's the type error. It red-screens the app when loading.
```
(property) ApolloPersistOptions<string>.storage: PersistentStorage<string>

Type '{ getItem(key: string): Promise<string>; setItem(key: string, value: string): Promise<string>; removeItem(key: string): Promise<void>; }' is not assignable to type 'PersistentStorage<string>'.
  Types of property 'setItem' are incompatible.
    Type '(key: string, value: string) => Promise<string>' is not assignable to type '(key: string, data: string) => void | Promise<void>'.
      Type 'Promise<string>' is not assignable to type 'void | Promise<void>'.
        Type 'Promise<string>' is not assignable to type 'Promise<void>'.
          Type 'string' is not assignable to type 'void'.ts(2322)

index.d.ts(14, 5): The expected type comes from property 'storage' which is declared here on type 'ApolloPersistOptions<string>'
```

If I ignore the type error then things work as expected.
```typescript
import { CachePersistor } from "apollo-cache-persist";
import ExpoFileSystemStorage from "redux-persist-expo-filesystem";

const persister = new CachePersistor({
  cache,
  // @ts-ignore
  storage: ExpoFileSystemStorage,
  debug: true
});
```

I'm pretty new to typescript so I can't be much more help than reporting the problem, sorry. 👍

**Comment by wtrocki** [comment]
Or `ExpoFileSystemStorage as PersistentStorage ` would work as well and be much nicer. It is really hard to track all nuances of the interfaces that are out there.
We have an unreleased version that fixed general typing problems on this.
