### ISSUE TITLE
persistCache writes to both user (user1&user2) caches

### ISSUE THREAD

**Issue by creambyemute** [apollographql/apollo-cache-persist#220]
Hey there,

I'm using apollo-cache-persists persistCache(...) to persist the apollo-cache on a user-basis.

The persisted caches are placed in and seperated by a folder (path/username/apollo-cache-persist)

On every successful login of a user I call `await persistCache(...)` which uses FSStorage (redux-persist-storage-fs) where the username is passed in.

**Problem:**

After logging in with user1, logging out, logging in with user2 and changing data it'll affect user1s cache as well, I guess because there are now multiple persistors due to my call to `persistCache` on every successful login.

Is there a way to circumvent/solve this without having to shut down & restart the app?

_Edit:_ I've solved my problem by using `RNRestart.Restart();` from `import RNRestart from "react-native-restart";` when logging out.
Is there another way to get rid of previous persistors when not setting up persistors myself but using `persistCache(...)`?

**Comment by wtrocki** [comment]
I think this is more related to actual app. If client is destroyed then cache should be wiped out. Using two separate keys will not work because when using a single client and InMemoryCache both persistors will be connected to the same InMemory cache data.

**Comment by creambyemute** [comment]
@wtrocki You are right, the client is created once when the app starts but not destroyed & recreated when logging out && logging in a new user.

So there is no way to remove the current persistor and I should rather destroy & recreate the whole client?

**Comment by wtrocki** [comment]
Persistor will be just persisting what is inMemoryCache so this problem is more related to wiping out your cache first and making sure it is persisted after will be the right choice. However if the requirement is to keep old/previous user data there you will need create new persistor with different key - like username prefix. On old persistor you will need to execute `pause` before creating new one as without it both persistors will append the data

**Comment by wtrocki** [comment]
Please let me know if  `pause` works for you. I will add this use case to docs

**Comment by wtrocki** [comment]
Actually I was wrong. Creating new cache and client should be much better option (along with purge method on client as there may be other issues like some queries or cache watchers still hanging out there

**Comment by creambyemute** [comment]
Yeah the intentis to keep the previous users data cache persisted so he could login again while being offline without having to sync everything again (data is per user).

Yeah I agree with you, that was totally the use-case and is the correct choice to do (destroy cloent and recreate with new cache).
A small disclaimer in the doc might help with that.
