### ISSUE TITLE
'write' trigger also on cache.reset()

### ISSUE THREAD

**Issue by ShockiTV** [apollographql/apollo-cache-persist#23]
Hi,
it seems from sources that on `client.resetStore()` we end up with `cache.reset()` so our patched method of `cache.write()` is probably not triggering.
If there is no observed query active, there will not be write operation and simple browser refresh would restore cache from storage for previous user even when we directly asked to invalidate it.

And I would probably consider handling it same way even in 'background' trigger.

**Comment by jamesreggio** [comment]
Hi @ShockiTV — good observation. We'll fix this.

**Comment by giautm** [comment]
Hi, any update?

**Comment by giautm** [comment]
Hi, I found a way to fix this issues. And I want to share. :p 
```javascript
import { AsyncStorage } from 'react-native';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { persistCache } from 'apollo-cache-persist';
import { HttpLink } from 'apollo-link-http';

const cache = new InMemoryCache({...});
persistCache({
  cache,
  storage: AsyncStorage,
});

// Continue setting up Apollo as usual.
const client = new ApolloClient({
  cache,
  link: new HttpLink({ uri: 'https://graphql.example.com' }),
});

// Purge persistor when the store was reset.
client.onResetStore(() => persistor.purge());
```

**Comment by lorensr** [comment]
Thanks @giautm—that works for me, despite a few errors like this being thrown on reset: 

![image](https://user-images.githubusercontent.com/251288/54850579-deae3700-4cbd-11e9-857f-c6997a6f33c0.png)

(githubStars is a root Query and Subscription field)

**Comment by wtrocki** [comment]
API changed slightly. Feel free to reopen if problem still persist
