### ISSUE TITLE
clarify documentation as to when to call persistCache

### ISSUE THREAD

**Issue by twelve17** [apollographql/apollo-cache-persist#239]
In the "web" section of the README, it states:

```
// await before instantiating ApolloClient, else queries might run before the cache is persisted
await persistCache({
  cache,
  storage: AsyncStorage,
});
```

But later, in the "How do I wait for the cache to be restored before rendering my app?" section, `persistCache` is called _after_ instantiating the client:

```
// Setup your Apollo Link, and any other Apollo packages here.

    const client = new ApolloClient({
      cache,
      ...
    });

    try {
      // See above for additional options, including other storage providers.
      await persistCache({
        cache,
        storage: window.localStorage,
      });
    } catch (error) {
      console.error('Error restoring Apollo cache', error);
    }
```

Is there something about RN that does not require the order of operations specified in the "web" section?

Related: https://github.com/apollographql/apollo-cache-persist/issues/62

**Comment by wtrocki** [comment]
I think it does not matter if await for persist cache will be done before or after client initialization. The most important is to do persistCache **before** making any queries or mutations. 

Generally speaking it is best to:

- Create cache object
- Hydrate cache from persistence using `persistCache`
- Create client using the cache

However for React/React Native apps I tend to drop client to provider and have separate component when I await for the cache to be rehydrated. 
This allows to render some UI/loading screen - otherwise people see white screen :)

**Comment by twelve17** [comment]
@wtrocki 

> I think it does not matter if await for persist cache will be done before or after client initialization.  The most important is to do persistCache before making any queries or mutations.

Wouldn't this be the case for both web and RN use cases?  Assuming the "web" example is using the top-level `await` proposal, which would block files that import the client file until the `await persistCache` is done, it should also work for RN, no?  

Conversely, if one is not using the top-level `await` proposal, and thus needs to propagate the `await`, as mentioned in https://github.com/apollographql/apollo-cache-persist/issues/62 and handled in the RN example by instantiating the Apollo client at the `App` level and awaiting for the `persistCache` before rendering, the same would also apply for "web" react too.  Maybe I'm missing some detail?

At the minimum, this comment should be changed if in the end it doesn't matter:

> // await before instantiating ApolloClient, else queries might run before the cache is persisted

I am more than open to offer a PR for documentation updates, but want to make sure I understand the motivation for / thinking behind both use cases first.

**Comment by wtrocki** [comment]
Agreed. Feel free to fix that.

**Comment by wtrocki** [comment]
Any update?

**Comment by twelve17** [comment]
@wtrocki I am not sure what to update this to, after the discussion in https://github.com/apollographql/apollo-cache-persist/issues/62 . Should we just use the hook example?

**Comment by wtrocki** [comment]
@twelve17 I would just put your last comment into readme so we will provide info how this cam be done. Hook example can be good as well

**Comment by msahu2595** [comment]
// await before instantiating ApolloClient, else queries might run before the cache is persisted
await persistCache({
cache,
storage: window.localStorage,
});

to

// await before instantiating ApolloClient, else queries might run before the cache is persisted
(async () => {
await persistCache({
cache,
storage: window.localStorage,
});
})();

Solved.

**Comment by msahu2595** [comment]
> In the "web" section of the README, it states:
> 
> ```
> // await before instantiating ApolloClient, else queries might run before the cache is persisted
> await persistCache({
>   cache,
>   storage: AsyncStorage,
> });
> ```
> 
> But later, in the "How do I wait for the cache to be restored before rendering my app?" section, `persistCache` is called _after_ instantiating the client:
> 
> ```
> // Setup your Apollo Link, and any other Apollo packages here.
> 
>     const client = new ApolloClient({
>       cache,
>       ...
>     });
> 
>     try {
>       // See above for additional options, including other storage providers.
>       await persistCache({
>         cache,
>         storage: window.localStorage,
>       });
>     } catch (error) {
>       console.error('Error restoring Apollo cache', error);
>     }
> ```
> 
> Is there something about RN that does not require the order of operations specified in the "web" section?
> 
> Related: #62

Change

`await persistCache({ cache, storage: window.localStorage, });`

to

`(async () => { await persistCache({ cache, storage: window.localStorage, }); })();`

Working fine. Solved.

**Comment by wodCZ** [comment]
I believe this can be closed since both examples and [F.A.Q.](https://github.com/apollographql/apollo-cache-persist/blob/master/docs/faq.md#how-do-i-wait-for-the-cache-to-be-restored-before-rendering-my-app) explain how this can be achieved.
