### ISSUE TITLE
Access CachePersistor via ApolloProvider?

### ISSUE THREAD

**Issue by pennyandsean** [apollographql/apollo-cache-persist#26]
Just a best practice question I suppose.  Is it possible to access the CachePersistor from anywhere lower down in a component tree, via a mechanism like ApolloProvider? Or is there some other neat way?  Would be cool for when doing manual persist triggering.  I've just used context for now.

**Comment by jamesreggio** [comment]
That's not a bad idea. Perhaps we could stash a reference on the Apollo Client for this purpose.

If anybody wants to implement, we'd be happy to review. (It will have to touch both `apollo-client` and `apollo-cache-persist`.) Otherwise, we'll consider adding in the next version of Apollo Client.

**Comment by wtrocki** [comment]
@pennyandsean There is a trigger feature that can help with this that will not require changes. We can have something like `manualTrigger` that will allow developers to attach that to React/Angular/Vue and additionally trigger persistence.

**Comment by wtrocki** [comment]
We could provide our own context provider but I found out that I usually already have some context in app where persistor might land - like Auth etc. Happy to reopen if you find it useful
