### ISSUE TITLE
trigger: 'background' on react-native behavior not as expected

### ISSUE THREAD

**Issue by geirman** [apollographql/apollo-cache-persist#28]
I've observed the following behavior with the following setup in my react native app...

```
persistCache({
    cache,
    storage: AsyncStorage,
    trigger: 'background',
  });
```

## unexpected behavior

1. User A logs in
2. User A sees their list of events (as expected)
3. User A logs out (JWT token & 'apollo-persist-cache' keys are explicitly deleted from localstorage)
4. User B logs in, expecting to see their list of events but instead sees User A's list. (unexpected)

NOTE: I'm pretty sure I tried both backgrounding the app and not backgrounding the app.

## assessment
I tracked this down to the persistCache function. When I commented it out, everything worked great. I'm not sure where user A's data is being rehydrated from because I explicitly delete the 'apollo-persist-cache' key from localstorage. if I trigger on 'write' everything works as expected as well, so that's how I've left things for now, realizing it may be a performance problem. So far, I've not noticed any performance issue though.

**Comment by jamesreggio** [comment]
Hi @geirman —

Are you familiar with [`client.resetStore()`](https://www.apollographql.com/docs/react/recipes/authentication.html#login-logout)?

In general, you're going to need to purge both the in-memory cache/client with `resetStore()` as well as the persisted cache upon logout. Session management is a fairly convoluted thing, and we could definitely do better in the next version of Apollo Client to coordinate all of these concerns.

(I also wrote up a lot more details about the various workings [here](https://github.com/apollographql/apollo-cache-persist/issues/34#issuecomment-371177206).)

Let me know if using `resetStore()` doesn't solve your problem and I'll be happy to reopen this.

**Comment by geirman** [comment]
Thanks @jamesreggio! This looks like it will be very helpful, and really appreciate you linking to more detail about how to properly (and completely) clear the cache. Very interesting reading! Convoluted for sure, but interesting and I'm grateful for the insight.
