### ISSUE TITLE
Component does not show persisted data on first render, but it does show it after an update

### ISSUE THREAD

**Issue by JulianMayorga** [apollographql/apollo-cache-persist#30]
I added `apollo-cache-persist` to a todo app, but it does not show persisted data when the app starts. The thing is that I checked the apollo dev tools and the data got persisted and restored correctly, but it does not get reflected in the UI. The restored data does get reflected in the UI after I update the app (add a todo).

![persist-bug](https://user-images.githubusercontent.com/843342/35973537-98c16a36-0cb4-11e8-985c-dfc512455119.gif)

[Here](https://github.com/wizardry-io/react-apollo-todomvc/tree/persist) is the repo, and [here](https://codesandbox.io/s/github/wizardry-io/react-apollo-todomvc/tree/persist) is a codesandbox with the todo app.

Is there something wrong about how I configured `apollo-cache-persist`? [Here](https://github.com/wizardry-io/react-apollo-todomvc/commit/5de5a90d19db59568083cf800243098a64713d0a#diff-14b1e33d5bf5649597cdc0e4f684daddR228) is the commit which added it, I used `persistCache`.

```
persistCache({
      cache,
      storage: window ? window.localStorage : global.localStorage
});
```

**Comment by jamesreggio** [comment]
Hi @JulianMayorga —

The persistor loads the cached data asynchronously, so you'll need to wait for it to finish before rendering if you don't want the initial load to appear empty.

`persistCache` returns a promise for this purpose. I suggest you try the following in your top-level app component:

```js
class App extends Component {
  state = {
    // ...
    loaded: false,
  };

  async componentWillMount() {
    // Initialize everything here, including Apollo.
    const cache = new InMemoryCache(/* ... */);
    await persistCache({
      cache,
      storage: window ? window.localStorage : global.localStorage,
    });
    this.setState({loaded: true});
  }

  render() {
    if (!this.state.loaded) {
      return <LoadingView />;
    }

    // ...
  }
}
```

Hope this helps!
