### ISSUE TITLE
0.2.0 not deployed on npm

### ISSUE THREAD

**Issue by screendriver** [apollographql/apollo-cache-persist#316]
I found out that the latest release [0.2.0](https://github.com/apollographql/apollo-cache-persist/releases/tag/0.2.0) was not deployed to npmjs.com

Is this by mistake or on purpose?

**Comment by wtrocki** [comment]
@screendriver I'm waiting for npm.js permission to publish to the original package. For the time being we are using the latest and greatest `apollo-cache-persist-dev` package

**Comment by wtrocki** [comment]
https://github.com/apollographql/apollo-cache-persist/issues/314

**Comment by screendriver** [comment]
Thank you for the information 👍 Closing this because duplication of https://github.com/apollographql/apollo-cache-persist/issues/314
