### ISSUE TITLE
compatibility for nativescript?

### ISSUE THREAD

**Issue by tafelnl** [apollographql/apollo-cache-persist#321]
Does `AsyncStorage` or another type also work with NativeScript?

**Comment by wtrocki** [comment]
Hi

It may require wrapping the storage interface. There are couple options for nativescript for storage. Which one we have in mind?

**Comment by tafelnl** [comment]
I am stulp a bit of a rookie when it comes to native script. But the ones I am aware of are https://docs.nativescript.org/ns-framework-modules/application-settings and https://github.com/techfort/LokiJS of which the latter seems most suitable to me.

Do you have any suggestions or can you maybe point me in the right direction?

**Comment by wtrocki** [comment]
LokiJS should work. Please let us know so we can add it to readme

**Comment by tafelnl** [comment]
Do you think I can just simply add LokiJS or do I have to use a wrapper like this one (https://github.com/paulhovey/loki-localforage-adapter) for localforage first? (Since the docs state localforage as an option)

**Comment by wtrocki** [comment]
Yes that will do the job - however haven't tried it

**Comment by tafelnl** [comment]
Okay, I am going to try and implement it today or tomorrow and get back to you as soon as I know something :)

**Comment by tafelnl** [comment]
By the way, with 
> Yes that will do the job
Do you mean, that just simply adding LokiJS should work, or that I indeed have to use a wrapper first?

**Comment by tafelnl** [comment]
As it turns out I was waaaay overthinking.
The solution is actually quite simple. See my comment here: https://github.com/pellejacobs/redux-persist-node-storage/issues/6#issuecomment-557451451
