### ISSUE TITLE
Cache purges on it's own ?

### ISSUE THREAD

**Issue by gotenxds** [apollographql/apollo-cache-persist#324]
Hello, for some reason cache purges after every write

![image](https://user-images.githubusercontent.com/3519520/71725346-33313600-2e3c-11ea-9a64-1a94948f78c3.png)

What causes purges to run? I tried to debug it but no where in my code do I call any of the purge methods

**Comment by wtrocki** [comment]
@gotenxds What is your:

- version
- config `maxSize` value 
- Storage engine

**Comment by gotenxds** [comment]
My version is 0.1.1
I have not config for maxSize I will try as suggested and report  
I use the default storage engine.

**Comment by gotenxds** [comment]
![image](https://user-images.githubusercontent.com/3519520/71725941-447b4200-2e3e-11ea-9200-8a98ce752311.png)
So I set maxSize to false and that does solve the issue, may I ask why tho ? as this issue did not exist just an hour ago and for the last couple of weeks I worked with apollo-cache-persist, I dont think my storage size is that big too

**Comment by wtrocki** [comment]
`108682` is more than 1 mb of cache that is default option for max size.
