### ISSUE TITLE
Version 0.2.0 is not published?

### ISSUE THREAD

**Issue by dan-cooke** [apollographql/apollo-cache-persist#329]
Just reading through docs and I really need to use `persistCacheSync` - but it appears the latest published version is 0.1.1?

https://www.npmjs.com/package/apollo-cache-persist

**Comment by wtrocki** [comment]
See https://github.com/apollographql/apollo-cache-persist/issues/316

there is separate dev package that has this change and many other fixes

**Comment by wtrocki** [comment]
Package name was changed to support apollo 3.0. Old package will stay to support apollo 2.0 etc.
