### ISSUE TITLE
How to cache queries in sqlite for React Native?

### ISSUE THREAD

**Issue by PritishSawant** [apollographql/apollo-cache-persist#338]
This not a bug in the library but I question from my side

I come from native app development background. I have used Native client of Apollo for Android and iOS and for caching my queries result I would use sqlite cache which is handled by the apollo client itself. I am trying to use graphql in React Native .I am using this package to cache my queries. I could find only two options, InMemoryCache and AsyncStorage. As far as I can understand InMemoryCache is somewhat like File IO and I don't understand why would any one store cache in Async Storage as it should only be used for small key value pair storage. How to use sqlite to cache my queries?. Does anybody have any reference for this. What is this Hermes thing they mentioned on their GitHub readme. Couldn't find how to use it. I thought Hermes is javascript engine to improve Android app performance

Also the cache doesn't seem to work. My client code is as follows

```
const client = new ApolloClient({
link: authLink.concat(httpLink),
cache: new InMemoryCache(),
});
```

And my query code is as follows

```
const {loading, error, data} = useQuery(HEALTH_CONSULTATION_QUERY, {
variables: {
patientId: '555',
doctorId: '123',
},
fetchPolicy: 'cache-first',
});
```

I fetched my queries for first time using newtork , then I closed the app completely. I disabled my network and then again opening the app, I don't see my cached result

**Comment by PritishSawant** [comment]
@wtrocki  Thanks for the reply Sorry but I can't see sqlite 
![Screenshot 2020-06-11 at 3 37 06 PM](https://user-images.githubusercontent.com/24708929/84372890-736dbf00-abf9-11ea-9806-3e9034285e50.png)
Are u talking about Async Storage?

**Comment by wtrocki** [comment]
you can provide your own storage - it is simple typescript interface that you will connect to the SQLLite. There is no need for such storage etc.

**Comment by PritishSawant** [comment]
@wtrocki  Thanks I had a looked at the Async Storage code. It does use sqlite on Android but for iOS I don't use it use any code for core data. It is in objective c and my lack of knowledge of it could be the reason but I think they use UserDefaults in iOS. Thanks for the reply. Also after integrating I am getting this 
![Screenshot 2020-06-11 at 4 11 12 PM](https://user-images.githubusercontent.com/24708929/84376248-71f2c580-abfe-11ea-8d9b-127488427574.png)

I added this to my code 
const cache = new InMemoryCache();

await persistCache({
  cache,
  storage: AsyncStorage,
});

**Comment by PritishSawant** [comment]
@wtrocki  No worries I figured it out. Thanks for your time and answers. Appreciate it

**Comment by georgiosd** [comment]
@wtrocki what about the 2MB limit on Android? Isn't that restriction still there?

**Comment by sagark1235** [comment]
Hi @wtrocki , Actually I was trying to make an offline first application with react-native and the local database is SQLite .I have backend developed in Django and the graphql . I am trying to sync the data from backend to frontend and vice versa . Would you please help how to procced with syncing of data.
