### ISSUE TITLE
Redis cache per query

### ISSUE THREAD

**Issue by Antonio-Laguna** [apollographql/apollo-cache-persist#340]
Hi here!

We've been using this package to be able to use Redis on the client side. The code is like this:

```js
const CreateClient = async (request, pageKey) => {
  const { server } = request;
  const config = server.settings.app;
  const fragmentMatcher = new IntrospectionFragmentMatcher({
    introspectionQueryResultData
  });

  const httpLink = ApolloLink.from([
    new RestLink({
      uri: config.apollo.chartApi,
      customFetch: fetch
    }),
    createHttpLink({
      uri: config.apollo.url,
      fetch
    })
  ]);

  const responseAfterware = new ApolloLink((operation, forward) => forward(operation)
    .map(response => transform(operation.operationName, response)));

  const cache = new InMemoryCache({ fragmentMatcher });
  const link = responseAfterware.concat(httpLink);

  if (config.apollo.cache.useRedis) {
    let key = `${config.apollo.cache.key}:${pageKey}`;

    await persistCache({
      cache,
      storage: server.redis,
      maxSize: config.apollo.cache.maxSize,
      key
    });
  }

  try {
    return new ApolloClient({
      connectToDevTools: false,
      ssrMode: true,
      link,
      cache
    });
  } catch (err) {
    console.log(err);
    console.trace();
    throw err;
  }
};
```

Subsequent page loads are instantly loading but because of page sharding, we're not able to leverage those calls on other pages (that would be repeated).

If we create a big cache object (using a single key), we're basically making the site lose the entire cache for the whole site whenever that cache expires. Also, we could hit the limit for Redis keys. 

We've thought about creating separate objects per page type but still, there are queries that are common for all pages (Menu, Footer and common widgets) so I'm wondering if there's any solution that can have each query cached or if there's any other thing I'm missing.

**Comment by wtrocki** [comment]
We are limited here by architecture of the cache plugin that writes do entire db.
I have been working on something like this in separate project.

**Comment by Antonio-Laguna** [comment]
Is that ready to be used @wtrocki ? I would be happy to test/contribute if you're open to that.

**Comment by wtrocki** [comment]
Basically solution would be to not rely on cache but instead using redis as store. 
There are couple options - redis can be done:

- per operation
- per type

I have been working on project that will store/fetch data per type, but this concept is so simple that you can get it done yourself in no time.

**Comment by jspizziri** [comment]
@wtrocki any updates here? If not I propose we close this issue for now.
