### ISSUE TITLE
Keep cache in sync between tabs?

### ISSUE THREAD

**Issue by FezVrasta** [apollographql/apollo-cache-persist#342]
Hi, what would be the recommended way to keep the Apollo cache in sync between multiple browser tabs? Is this in scope for this library or should I look elsewhere?

**Comment by FezVrasta** [comment]
For now what I did was to add the following code to my app:

```js
  window.addEventListener('storage', () => {
    let crossTabCache;
    try {
      crossTabCache = JSON.parse(storage.getItem(CACHE_KEY));
    } catch (err) {
      return;
    }
    const localCache = cache.extract();

    cache.restore({ ...localCache, ...crossTabCache });
  });
```

It seems to work fairly well, but I haven't tested it extensively so far.

**Comment by proIT324** [comment]
Although apollo cache changes, `useQuery` isn't fired at all.

**Comment by FezVrasta** [comment]
yeah I noticed, I opened a topic in the Apollo repo, it seems a bug to me.
https://github.com/apollographql/apollo-client/discussions/6956

**Comment by FezVrasta** [comment]
I tried to add a `cache.broadcastWatches();` after `cache.restore`, this seems to trigger the refresh of the components with the new data, but it takes approx 5 seconds in my app, that's less than ideal...

**Comment by proIT324** [comment]
I tried to run `apolloClient.reFetchObservableQueries()` after `cache.restore()`. It seems to be working fine.

**Comment by FezVrasta** [comment]
> I tried to run `apolloClient.reFetchObservableQueries()` after `cache.restore()`. It seems to be working fine.

That calls the backend again, it doesn't just read from the cache.

**Comment by proIT324** [comment]
Where is `broadcastWatches()` from?

**Comment by FezVrasta** [comment]
It's a protected method from the InMemoryCache class, it's not a public method.

**Comment by proIT324** [comment]
It prevents the client from calling the backend. Thanks! 👍

**Comment by FezVrasta** [comment]
For some reason after I deployed the app this fix didn't work, it seems to work only in the development build 😕

**Comment by proIT324** [comment]
Really? I'm gonna try with my app. BTW, this package is no longer maintained?

**Comment by jspizziri** [comment]
@FezVrasta @proIT324 ,

This package is still maintained. Closing this for now due to inactivity. Please let me know if it needs to be opened back up.

**Comment by FezVrasta** [comment]
Inactivity of what kind? What kind of activity would you like to see?

**Comment by jspizziri** [comment]
As was covered in detail in https://github.com/apollographql/apollo-cache-persist/issues/411 by @wodCZ and @wtrocki.

There are multiple challenges with multi tab cache persistence that this package is not currently intended to solve. If you feel adamant that this package should support it out of the box then I'd ask that you propose a design and subsequently submit a PR.

My instinct however is that this is something best solved by an external library working in concert with this one. If that's the case then if such a library exists I'd be happy to update the FAQ and link over to it for people who are trying to solve this issue.

**Comment by paulieDOTjs** [comment]
I know this is old and forgotten but for what it's worth this is what has worked for me.

```
useEffect(() => {
    const handleStoreReset = () => {
      try {
        const stringCache = localStorage.getItem(APOLLO_CACHE_KEY);
        if (!stringCache) return;
        const crossTabCache = JSON.parse(stringCache);
        const localCache = cache.extract();

        cache.restore({ ...localCache, ...crossTabCache });
      } catch (err) {
        console.error(err);
      }
    };

    window.addEventListener('focus', handleStoreReset);
    return () => {
      window.removeEventListener('focus', handleStoreReset);
    };
  }, [client]);
```
