### ISSUE TITLE
@apollo/client 3.0 incompatibility with apollo-cache-persist

### ISSUE THREAD

**Issue by arochadaniel** [apollographql/apollo-cache-persist#343]
**Intended outcome:** update all my dependencies to use @apollo/client 3.0, including the persistence of the storage using LocalStorage

**Actual outcome:** when I try to initialize `persistCache` with the cache exported from `@apollo/client`, I get the following TypeScript error:

```
Property 'writeData' is missing in type 'InMemoryCache' but required in type 'ApolloCache<NormalizedCacheObject>'.ts(2741)

cache.d.ts(22, 5): 'writeData' is declared here.

index.d.ts(13, 5): The expected type comes from property 'cache' which is declared here on type 'ApolloPersistOptions<NormalizedCacheObject>'
```
I tried to type cast the cache `as any` but the cache on localStorage doesn't write anything, I guess the missing property `writeData` comes from the new inmutability in the 3.0 client, and it broke the way that apollo-cache-persist writes data

**How to reproduce the issue:** while using TypeScript, install @apollo/client 3, instantiate a new client, try to persist cache with the InMemoryCache exported from `@apollo/client`

**Comment by cesargdm** [comment]
<img width="731" alt="Screen Shot 2020-08-26 at 7 02 58 PM" src="https://user-images.githubusercontent.com/10179494/91368456-c30e6080-e7ce-11ea-9320-a2892bf5eb09.png">
Facing same issue

**Comment by wtrocki** [comment]
Merged compatiblity to master. Working on release.
