### ISSUE TITLE
database or disk is full

### ISSUE THREAD

**Issue by Hamza-Khurshid** [apollographql/apollo-cache-persist#345]
"[apollo-cache-persist] Error persisting cache Error: database or disk is full (code 13 SQLITE_FULL[13])"
Getting this error on android when large amount of data is loaded but I am sure my phone has large disk space.
Some extra info that I got is:
  Called from: node_modules/@react-native-community/async-storage/src/AsyncStorage.native.js in apply.

**Comment by wtrocki** [comment]
Is is probably limit of indexed db. We cannot do much about it apart from enabling filtering of the stored data.

**Comment by Hamza-Khurshid** [comment]
> Is is probably limit of indexed db. We cannot do much about it apart from enabling filtering of the stored data.

Do you mean we need to reduce the amount of data?

**Comment by wtrocki** [comment]
I think that you would probably persist just a fraction of the data and filter not needed objects. 
This can be done by overriding cache save method

https://github.com/apollographql/apollo-cache-persist/blob/master/src/onCacheWrite.ts

Alternatively, we can use `maxSize` parameter to wipe out cache once it fills but I get that for your case this will happen so frequently that will invalidate persitence. 

We need some simple function that will allow people to filter out cache - any contributions welcomed

**Comment by wtrocki** [comment]
Closing. Feel fee to reopen if needed
