### ISSUE TITLE
Apollo cache disappears from local storage on every write action.

### ISSUE THREAD

**Issue by proIT324** [apollographql/apollo-cache-persist#346]
I applied this package to sync apollo cache with 2 different tabs. In the original tab, several subscriptions update this cache and the second tab should show all cache updates. When a subscription fire updates cache, the cache in local storage becomes available for 10 sec and disappears until the next subscription fire. Because of this issue, I can't have the correct data in the second tab. Any good solution? 

```js
const cache = new InMemoryCache({...});

const checkCache = async () => {
  await persistCache({
    cache,
    storage: window.localStorage,
  });
}

checkCache();

const client = new ApolloClient({
  cache,
  ...
});
```

**Comment by FezVrasta** [comment]
By default this extension doesn't sync cache across tabs, it only restores cache from your storage of choice on load.

**Comment by wtrocki** [comment]
yep.. Having 2 different tabs open will not sync them. 

Cache is just dumping memory. So it will be the race condition between two tabs (usually ending with problems. Support for two tabs could involve using another persistence and checking it before, but this will still disable persistence for the (second tab)
