### ISSUE TITLE
[Clarification] Is cache scoped to instance

### ISSUE THREAD

**Issue by JasonLi914** [apollographql/apollo-cache-persist#36]
This is probably an obvious question, but I wanted to get clarification on caching in apollo and if it is scoped to the apollo-client instance it's passed to. So if one was to have multiple apollo-clients and wanted to use CachePersistor to purge the cache, it would only purge the cache for the particular cache it is scoped too, right? I just want to make sure that calling purge on one in-memory-cache only purges that particular instance's cache in the browser.

**Comment by jamesreggio** [comment]
Hi @JasonLi914 — you're correct. The cache persistor is scoped to the cache that it's attached to. That is to say, when you call `persistor.purge()`, it will only delete the `key` in the storage provider that it is managing.

If you have multiple caches and persistors, you need to pass a unique `key` to each persistor so they don't both use the same default value and write over each other.

Please let me know if that answers your question.

**Comment by JasonLi914** [comment]
@jamesreggio - Ah perfect, I missed the `key` API, so that clears up the confusion, thanks!
