### ISSUE TITLE
Incompatible with fetchMore

### ISSUE THREAD

**Issue by crubier** [apollographql/apollo-cache-persist#37]
When using fetchMore for pagination as explained in 
https://www.apollographql.com/docs/react/recipes/pagination.html#fetch-more

Only the first results (those not obtained through fetchMore) are persisted. Additional results from fetchMore are not persisted

**Comment by jamesreggio** [comment]
Hi @crubier — I think this is actually a problem with `InMemoryCache`, which does not correctly store the (query, variables, results) tuple of the `fetchMore` operation. You can confirm this with the following steps:

1. Disable `apollo-cache-persist`
2. Run your app
3. Visit a screen
4. Cause it to `fetchMore`
5. Leave that screen
6. Go offline
7. Return to that screen
8. Cause it to `fetchMore`

If the cache was storing `fetchMore` data properly, it should be available in Step 8 while you're offline, but I'm 99% certain that it won't be. Anecdotally, I've encountered this problem before, but I haven't taken the time to isolate it and file an issue on [`apollo-client`](https://github.com/apollographql/apollo-client).

Perhaps you could file it there?

**Comment by jamesreggio** [comment]
I'm going to close this issue. If you try the steps above and end up discovering that this issue only repros when `apollo-cache-persist` is included, please comment and we'll dig in deeper.

**Comment by nuragic** [comment]
Hi! 

> Anecdotally, I've encountered this problem before, but I haven't taken the time to isolate it and file an issue on apollo-client.

@jamesreggio I'm struggling with this same problem I believe... As far as I can see, the cache doesn't contains those queries that were triggered by `fetchMore`... Do you managed to solve it or have you reported it to `apollo-client`? Thanks!
