### ISSUE TITLE
Question: Can i restore cache and then refetch all queries on the background?

### ISSUE THREAD

**Issue by DamirAhm** [apollographql/apollo-cache-persist#398]
So my question in the title. I need to purge the previous cache, then fetch new data, and persist it without worrying user (without showing loaders). Because now if I change something from the different device I can't see changes on others. I'm pretty new in Apollo, so the question may be very dumb. Thanks in advance.

**Comment by wodCZ** [comment]
This sounds like a job for `fetchPolicy`. Apollo Client now uses `cache-first` fetch policy as a default (see [documentation](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy)). That means, when there's cached result, use it without querying the server.

You might want to set the policy to `cache-and-network` - that's "when there's cached result, use it, but also ask server for new data".

**Comment by jspizziri** [comment]
As @wodCZ this sounds like it’s solved with fetch policies.
