### ISSUE TITLE
State of whitelist / blacklist ?

### ISSUE THREAD

**Issue by mbret** [apollographql/apollo-cache-persist#403]
Hello, I was wondering what is the state of this wanted feature ?

I am currently developing an offline first app and use the cache as primary state. That being said need to filter out some of the fields because. 

For example I have a boolean field which define the state of one of my button. It's a button that trigger a sync. While the sync is happening the button is disabled. Of course this process can takes time and if the user reload the page while the button is disabled it will be disabled when the page is refreshed. The user is then blocked and cannot press the button.

What I do right now as a general pattern in my app is that before starting the app I will use `writeQuery` for every field that I do not want to be persisted and assign them their default value. Basically I will override whatever value come from the local storage with the default one. This works well but requires boilerplate and maintenance.

This kinda looks like this.
```
const app = new Apollo(...)

await resetBlacklistCacheValues(app)

return app

```

Anyway I was wondering if a BL/WL was still on the box or if we should just find some workaround such as mine ?

**Comment by wtrocki** [comment]
@mbret There is PR that is there for quite some time. 
Would you be interested in taking look if that is something that will sort things out for you:

https://github.com/apollographql/apollo-cache-persist/pull/71

**Comment by mbret** [comment]
Sure, I could take a look

**Comment by jspizziri** [comment]
@mbret , you should be able to achieve your goals with the ‘persistenceMapper’. Let me know if you still have issues.
