### ISSUE TITLE
No exported member 'AsyncStorageWrapper'.

### ISSUE THREAD

**Issue by KhubaibQaiser** [apollographql/apollo-cache-persist#404]
Hi, I am trying to integrate this library with react-native. I am getting the following error when trying to import `AsyncStorageWrapper` from the lib.
```Module '"../../../node_modules/apollo3-cache-persist/lib"' has no exported member 'AsyncStorageWrapper'.```

I have also tried the examples but they also seem to have the same issue. How can I resolve this?

**Comment by wodCZ** [comment]
Hi,
a PR introducing storage wrappers was merged a while ago, but new version matching that described in readme wasn't released to NPM yet.

Please follow this version readme: https://github.com/apollographql/apollo-cache-persist/blob/91b8dec02580471b1d6f6fff7d6c6727b7e5869c/README.md

That should work just fine 😉

**Comment by wtrocki** [comment]
@wodCZ I will release that now using dev branch for tesing.

**Comment by wtrocki** [comment]
npm notice name:          apollo3-cache-persist                   
npm notice version:       0.9.0
