### ISSUE TITLE
Question: does the package support Ionic Offline Storage (the enterprise version of Ionic Storage)?

### ISSUE THREAD

**Issue by lauromueller** [apollographql/apollo-cache-persist#407]
I'm not sure whether this would be supported since Ionic Offline Storage (enterprise) is fundamentally different from basic key-value pairs. Is there any clear guidelines about the support to the enterprise version of the package?

**Comment by wtrocki** [comment]
@lauromueller we have new wrapper concept so any storage can be adapted. 
Ionic offline storage (enterprise) might be done on your side or even contributed to this repository (as wrapper)

See docs:
https://github.com/apollographql/apollo-cache-persist#react-native

**Comment by lauromueller** [comment]
@wtrocki understood! Thanks for the timely response.
