### ISSUE TITLE
Apollo Cache Persist in Vue 3 and VueApollo 4

### ISSUE THREAD

**Issue by Gyurmatag** [apollographql/apollo-cache-persist#408]
Hi!

Can somebody give us an example on how to properly use Apollo Cache Persist in Vue 3 and VueApollo4?

Thank you very much!

**Comment by wtrocki** [comment]
Would you have any recommendations for sample Vue app to use as base?

**Comment by Gyurmatag** [comment]
I am looking for an example with Vue 3 and VueApollo 4!

**Comment by jspizziri** [comment]
@Gyurmatag , if you could submit a PR with the scaffolding for a vue example app I can layer in the persist code.
Closing for now but will reopen if there’s interest.
