### ISSUE TITLE
A way to sync cache on new window open

### ISSUE THREAD

**Issue by Marcinthedev** [apollographql/apollo-cache-persist#411]
Is there any way to keep the cache sync if I open a new window from app, trigger a query, close it and the open same window with cached data again? Maybe it's not possible, but as I've read somewhere in the issues keeping tabs synced is possible right?

**Comment by wodCZ** [comment]
If you talk about doing some queries a window, closing the window and opening the window again, this should work as you expect (we're talking at most one tab opened at once). If this is the case, make sure you've followed the setup examples correctly and check that there's not error in your console. Also, you can inspect that the cache is saved in the localStorage using Chrome debugger if you're using localStorage wrapper.

If you're talking about two separate tabs with the same app, that's a different story. This was already discussed in issue #342 and #346.

> By default this extension doesn't sync cache across tabs, it only restores cache from your storage of choice on load.

Having two tabs open will not share the cache (and is not in scope of this library).
