### ISSUE TITLE
Cannot persistCache with AsyncStorageWrapper(AsyncStorage)

### ISSUE THREAD

**Issue by mikeportanova** [apollographql/apollo-cache-persist#412]
I am implementing persistCache exactly as outlined in the React w/ Hooks example, but when I run my app, I receive:
> undefined is not a constructor (evaluating 'new _apollo3CachePersist.AsyncStorageWrapper(_asyncStorage.default)')

The only difference between my implementation and the docs is that I am properly importing AsyncStorage from the new repository @react-native-async-storage/async-storage (rather than from react-native-community).

Anyone experiencing this? I have reset Metro cache, cleaned build folder, etc. Problem persists.

The relevant part of the docs

`
persistCache({
      cache,
      storage: new LocalStorageWrapper(window.localStorage)
    }).then(() => {
      client.onResetStore(async () => cache.writeData({ data: initData }));
      setClient(client);
    });
`

I have tried using then() and I have tried awaiting persistCache. All of them trigger this error.

**Comment by wodCZ** [comment]
It looks like the hooks example is outdated. I've set-up a [codesandbox example](https://codesandbox.io/s/apollo3-cache-persistasyncstorage-412-or9tv?file=/src/App.tsx). Can you please check the code, imports, libraries and versions?

Imports should look like this:
```ts
import { persistCache, AsyncStorageWrapper } from "apollo3-cache-persist";
import AsyncStorage from "@react-native-async-storage/async-storage";
```

then the call itself:
```ts
    persistCache({
      cache,
      storage: new AsyncStorageWrapper(AsyncStorage)
    });
```

In the example it looks like there's Apollo Client version 2 used, which is no-longer compatible with apollo3-cache-persist I believe, or at least `cache.writeData` was removed if I'm not mistaken.

**Comment by wtrocki** [comment]
@wodCZ Yes. Sounds like docs is no longer up to date

**Comment by mikeportanova** [comment]
Hi there,

Thanks for the quick turnaround on the docs. I have re-implemented per the updated react native example, but the exact same problem persists. I have tried removing my middleware and upload link, but the problem remains. Same error as I posted before.

`
import {
  ApolloClient,
  ApolloProvider,
  HttpLink,
  from,
  useMutation,
  ApolloLink,
} from '@apollo/client';
import {setContext} from '@apollo/client/link/context';
import {createUploadLink} from 'apollo-upload-client';
import {
  persistCache,
  CachePersistor,
  AsyncStorageWrapper,
} from 'apollo3-cache-persist';

const httpLink = createUploadLink({
  uri: DEV_DEVICE_API + '/graphql',
  fetch,
});

const authMiddleware = setContext(async (_, {body, headers}) => {
  const token = await AsyncStorage.getItem('token');

  //Attach sessionType (athlete vs instructor) to each request to API
  const sessionType = await AsyncStorage.getItem('sessionType');

  return {
    headers: {
      ...headers,
      Authorization: `JWT ${token}`,
      SessionType: sessionType,
    },
  };
});

const App = () => {
  const [client, setClient] = useState(undefined);
  const [persistor, setPersistor] = useState(undefined);
  useEffect(() => {
    async function init() {
      try {
        const cache = new InMemoryCache();
        let newPersistor = new CachePersistor({
          cache,
          storage: new AsyncStorageWrapper(AsyncStorage),
          debug: __DEV__,
          trigger: 'write',
        });
        await newPersistor.restore();
        setPersistor(newPersistor);
        setClient(
          new ApolloClient({
            link: from([authMiddleware, httpLink]),
            cache,
          }),
        );
      } catch (e) {
        console.log(e.message);
      }
    }
    init();
  }, []);


  const clearCache = useCallback(() => {
    if (!persistor) {
      return;
    }
    persistor.purge();
  }, [persistor]);

  if (!client) {
    return <ContentLoader />;
  }
  console.log('wtf', client);
  return (
    <SafeAreaProvider>
      <ApolloProvider client={client}>
        <AuthController />
      </ApolloProvider>
    </SafeAreaProvider>
  );
};

export default App;
`

**Comment by wodCZ** [comment]
Closing this, as the original issue was resolved.
