### ISSUE TITLE
How's the hooks example supposed to work?

### ISSUE THREAD

**Issue by FezVrasta** [apollographql/apollo-cache-persist#417]
Hi, I tried to follow [this example](https://github.com/apollographql/apollo-cache-persist#react-using-hooks) but Apollo complains about the uninitialized Apollo client.

How's the example supposed to work?

**Comment by wtrocki** [comment]
Check examples folder

**Comment by FezVrasta** [comment]
Oh ok I see, [this is missing in the README](https://github.com/apollographql/apollo-cache-persist/blob/master/examples/web/src/index.tsx#L107-L109)
