### ISSUE TITLE
Serialize: false option is not working as expected

### ISSUE THREAD

**Issue by PMCorbett** [apollographql/apollo-cache-persist#419]
Setting `serialize: false` as an option doesn't appear to work correctly. I believe the expected behaviour is that the store would be passed the whole cache as an unserialized object, but instead it receives `[object Object]`.

I believe this is because of the change made in this pull request https://github.com/apollographql/apollo-cache-persist/pull/388 to bring the storage api in line with the Web Storage api. 

However the issue with this is when the store gets large, parsing and stringifying all that JSON becomes very resource intensive, which is why I imagine the serialize option was added.

**Comment by wtrocki** [comment]
Good catch
