### ISSUE TITLE
Version 0.10.0 published, but no changes here

### ISSUE THREAD

**Issue by cranberyxl** [apollographql/apollo-cache-persist#424]
It is suspect that there are updates to npm, but no changes here. Is there a new repo where this is being managed?

**Comment by wtrocki** [comment]
you mean "apollo3-cache-persist" ?

**Comment by cranberyxl** [comment]
Correct: https://www.npmjs.com/package/apollo3-cache-persist/v/0.10.0 Is there a separate github repo? npm points here

**Comment by wtrocki** [comment]
That is the repository we have added 3 as we have migrated package to Apollo 3.0 and still wanted to have support for version 2 (which is historic at this point)

**Comment by cranberyxl** [comment]
Where can I see the code changes and release notes for `0.10.0`?

**Comment by wtrocki** [comment]
https://github.com/apollographql/apollo-cache-persist/compare/0.9.0...0.10.0

**Comment by cranberyxl** [comment]
Thanks for that tag. So, this is just publishing changes from March?

**Comment by wtrocki** [comment]
Yes
