### ISSUE TITLE
[QUESTION] apollo3-cache-persist vs. @apollo/cache-persist

### ISSUE THREAD

**Issue by jspizziri** [apollographql/apollo-cache-persist#425]
Since the convention in the rest of the Apollo ecosystem for v3 is that v3 packages are published under the `@apollo/` namespace, would it be a good idea to publish this package as `@apollo/cache-persist` for v3?

**Comment by wtrocki** [comment]
@apollo packages are officially supported product.
apollo3-cache-persist is still a community project.
