### ISSUE TITLE
LocalStorageWrapper broken on 0.10.0

### ISSUE THREAD

**Issue by blaenk** [apollographql/apollo-cache-persist#426]
Using the same code from the example:

https://github.com/apollographql/apollo-cache-persist/blob/7bcb322a32aafb088afcf2c21c1ebe793409d8e3/examples/web/src/index.tsx#L76-L83

And from the readme, upgrading to 0.10.0 without any code changes breaks the use of `LocalStorageWrapper`:

```
TS2322: Type 'LocalStorageWrapper' is not assignable to type 'PersistentStorage<PersistedData<NormalizedCacheObject>>'.
Types of property 'setItem' are incompatible.
Type '(key: string, value: string) => void | Promise<void>' is not assignable to type '(key: string, value: PersistedData<NormalizedCacheObject>) => void | Promise<void> | PersistedData<NormalizedCacheObject> | Promise<...>'.
Types of parameters 'value' and 'value' are incompatible.
Type 'PersistedData<NormalizedCacheObject>' is not assignable to type 'string'.
Type 'null' is not assignable to type 'string'.
```

The types don't seem to line up. I think the problem is that the type parameter for `CachePersistor` is in this case `NormalizedCacheObject` so the options are `ApolloPersistOptions<NormalizedCacheObject>` which would then expect `storage: PersistentStorage<PersistedData<NormalizedCacheObject>>`, whereas `LocalStorageWrapper` would provide `PersistentStorage<string>`.

By the way, it might be helpful to build the examples as part of CI to serve as a canary for when these things happen.

**Comment by wtrocki** [comment]
On holidays for 2 weeks with limited access to workstation. Would using any for interface work as workaround until we fix this?
Good hint to build examples. Thank you

**Comment by blaenk** [comment]
No rush at all! I simply stuck with the previous version for now, just thought I'd make you all aware of this.

Thank you and enjoy your holiday!

**Comment by Micloroc** [comment]
Just to add some info, same happens for IonicStorageWrapper. I think all wrappers are broken in 0.10.0.

Anyway, awesome library, thanks for your work and enjoy holidays!

**Comment by blaenk** [comment]
cc @PMCorbett regarding what I think may be the relevant commit 8a1563401bab5ae854e7611c833ea64fff20a50d via https://github.com/apollographql/apollo-cache-persist/pull/420

No pressure, just adding information.

**Comment by wtrocki** [comment]
I could not figure out how to fix it apart from adding any as option to every storage abstraction which defeats the purpose of having generics at all.

**Comment by maximeg** [comment]
Same here since 0.10, 0.11 didn't solve it:

```
node_modules/apollo3-cache-persist/lib/storageWrappers/LocalForageWrapper.d.ts:7:5 - error TS2416: Property 'setItem' in type 'LocalForageWrapper' is not assignable to the same property in base type 'PersistentStorage<string | object>'.
  Type '(key: string, value: string) => void | Promise<void>' is not assignable to type '(key: string, value: string | object) => string | void | object | Promise<void> | Promise<string | object>'.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'string | object' is not assignable to type 'string'.
        Type 'object' is not assignable to type 'string'.

7     setItem(key: string, value: string): void | Promise<void>;
      ~~~~~~~

src/graphql/client.ts:79:5 - error TS2322: Type 'LocalStorageWrapper' is not assignable to type 'PersistentStorage<PersistedData<NormalizedCacheObject>>'.
  Types of property 'setItem' are incompatible.
    Type '(key: string, value: string) => void | Promise<void>' is not assignable to type '(key: string, value: PersistedData<NormalizedCacheObject>) => void | Promise<void> | PersistedData<NormalizedCacheObject> | Promise<...>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'PersistedData<NormalizedCacheObject>' is not assignable to type 'string'.
          Type 'null' is not assignable to type 'string'.

79     storage,
       ~~~~~~~

  node_modules/apollo3-cache-persist/lib/types/index.d.ts:15:5
    15     storage: PersistentStorage<PersistedData<TSerialized>>;
           ~~~~~~~
    The expected type comes from property 'storage' which is declared here on type 'ApolloPersistOptions<NormalizedCacheObject>'
```

**Comment by wtrocki** [comment]
We need to add ` | any` to every storage we have. Volunteers?
