### ISSUE TITLE
MMKVStorageWrapper needs to handle null OR TypeScript typings are wrong

### ISSUE THREAD

**Issue by hitsthings** [apollographql/apollo-cache-persist#428]
```js
await persistCache({
    cache,
    storage: new MMKVStorageWrapper(apolloCacheStorage),
});
```
The above shows an error on the `storage` property:

```
Type 'MMKVStorageWrapper' is not assignable to type 'PersistentStorage<PersistedData<NormalizedCacheObject>>'.
  Types of property 'setItem' are incompatible.
    Type '(key: string, value: string) => void | Promise<void>' is not assignable to type '(key: string, value: PersistedData<NormalizedCacheObject>) => void | Promise<void> | PersistedData<NormalizedCacheObject> | Promise<...>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'PersistedData<NormalizedCacheObject>' is not assignable to type 'string'.
          Type 'null' is not assignable to type 'string'.ts(2322)
```

I believe MMKV can indeed only handle strings using `setItem`. Not sure the semantics of null here.

**Comment by wodCZ** [comment]
Hi @hitsthings, thanks for reporting.

This is an issue introduced in v0.10.0 and is already discussed in #426.

The problem is in type definitions that were generalised in #420, the storage wrapper should work without a problem.
You can `@ts-ignore` this at the moment, and subscribe to #426 for updates.

**Comment by hitsthings** [comment]
Ah, sounds good, thank you! Good to know it's just the TS.

Will close this then to be tracked in #426 . Cheers!
