### ISSUE TITLE
Help: how to control what need to be persisted?

### ISSUE THREAD

**Issue by alexmbp** [apollographql/apollo-cache-persist#43]
Hi there! I need to control my cache by saving something in secure storage (https://www.npmjs.com/package/redux-persist-sensitive-storage), something in AsyncStorage (react-native). How can I control it?

- [x] feature
- [x] good first issue

**Comment by jamesreggio** [comment]
Hi @alexmbp —

It's not possible to split the cache between two separate storage providers.

However, if you want to use secure storage for the entire cache, you should be able to just pass an instance of the `redux-persist-sensitive-storage` provider to `persistCache`, like this:

```js
import createSensitiveStorage from "redux-persist-sensitive-storage";
// ... 
persistCache({store, storage: createSensitiveStorage(options) });
```

Does that answer your question?

**Comment by alexmbp** [comment]
I’m currently using this provider. Well. If that’s not possible for now - I’ll start to read how to ignore something from cache. Thank you!

**Comment by lucasconstantino** [comment]
Some work I've recently publish on that matter: https://github.com/TallerWebSolutions/apollo-cache-instorage

**Comment by mikaoelitiana** [comment]
> Hi @alexmbp —
> 
> It's not possible to split the cache between two separate storage providers.
> 
> However, if you want to use secure storage for the entire cache, you should be able to just pass an instance of the `redux-persist-sensitive-storage` provider to `persistCache`, like this:
> 
> ```js
> import createSensitiveStorage from "redux-persist-sensitive-storage";
> // ... 
> persistCache({store, storage: createSensitiveStorage(options) });
> ```
> 
> Does that answer your question?

@jamesreggio this snippet does not work for me, I get an error : 

```
Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'setItem' of undefined
TypeError: Cannot read property 'setItem' of undefined
    at Object.setItem$
...
```
