### ISSUE TITLE
Feature Request update "@apollo/client"

### ISSUE THREAD

**Issue by cjohn001** [apollographql/apollo-cache-persist#442]
Hello together,
I am following the development here since a while. The current client version seems to be a rather old one, and I seem to be not able to get apollo-cache-persist running with 3.3.x versions of the client. I think it is already on 3.4
"@apollo/client": "3.2.4"

Are there any plans to also support more recent versions of apollo client?

**Comment by wodCZ** [comment]
Hi @cjohn001, is there some issue with the new release?
The apollo client is a peer dependency, so it shouldn't intercept with the installed version.

**Comment by cjohn001** [comment]
@wodCZ : Thanks for the reply. I currently have problems building apollo-angular@next and suspected this package to be responsible. But you are right, I could build against 3.4 version of apollo-client. Will close the issue as the problem seems to be a different one.
