### ISSUE TITLE
Can't fetch data from local storage

### ISSUE THREAD

**Issue by alucardu** [apollographql/apollo-cache-persist#445]
I'm trying to grab some data on my logged in user with `apollo3-cache-persist`. 

```
// index.tsx

  const cache = new InMemoryCache();

  await persistCache({
    cache,
    storage: window.localStorage,
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache,
  });
 ```

```
// cache.tsx

export const currentUserVar: ReactiveVar<ICurrentUser> = makeVar<ICurrentUser>({
  id: 1,
  email: '',
  loggedIn: false,
});

export const cache: InMemoryCache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        User: {
          read() {
            return currentUserVar();
          },
        },
      },
    },
  },
});
```

```
// resolvers.ts

const ReturnCurrentUser = gql`
  query CurrentUser {
    user {
      email
    }
  }
`;
```

```
// movieOverview.tsx

  const {loading, error, data} = useQuery(resolvers.queries.ReturnCurrentUser, {fetchPolicy: 'cache-only'});
  console.log(loading, error, data);
```

```
// login.tsx

      currentUserVar({
        email: data.loginUser.currentUser.email,
        id: data.loginUser.currentUser.id,
        loggedIn: true,
      });
      window.localStorage.setItem('token', data.loginUser.token);
```

![image](https://user-images.githubusercontent.com/779921/131415702-770061d9-3c74-45ee-8405-ec0fe9667980.png)

In the `cache.tsx` I have a reactive variable that stores the user data. The typePolicy should return the `currentUserVar()` value. But I keep getting a `undefined`. I'm probably mixing up several things to get this working.

**Comment by wodCZ** [comment]
apollo3-cache-perist doesn't support reactive variables (see discussion in #361). 

My guess is that the typePolicy is overriding the cached value with the reactive variable. You might find few approaches on persisting reactive variables in the linked issue.

---
PS: I've noticed you don't have the localstorage wrapped in wrapper (see [readme](https://github.com/apollographql/apollo-cache-persist#web)):
```ts
import { persistCache, LocalStorageWrapper } from 'apollo3-cache-persist';

const cache = new InMemoryCache({...});

await persistCache({
  cache,
  storage: new LocalStorageWrapper(window.localStorage),
});
```
But that isn't the root of your issue.

**Comment by jspizziri** [comment]
@wodCZ @alucardu , this can be closed yeah?

**Comment by wodCZ** [comment]
I think so, @alucardu let me know if this needs to be reopened.
