### ISSUE TITLE
Overwrites my Apollo Client Provider Default Options

### ISSUE THREAD

**Issue by IsaacTrevino** [apollographql/apollo-cache-persist#454]
My default options seem to be ignored when using 
```javascript
const client = new ApolloClient({
  link: link,
  cache: cache,
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      errorPolicy: 'ignore',
    },
    query: {
      fetchPolicy: 'network-only',
      errorPolicy: 'all',
    },
    mutate: {
      errorPolicy: 'all'
    }
  },
  connectToDevTools: true
});

persistCache({
  cache,
  storage: new LocalForageWrapper(localForage),
  maxSize: false,
}).then(() => {
  client.onResetStore(async () => cache.writeData({ data: initData }));
  setApolloClient(client);
});
```

This code causes my apollo client to forcefully use cache-first as its fetch policy for all queries.
Is there a way to troubleshoot this issue, or am I not setting the `persistCache` correctly.

I am using libraries:
`"@apollo/client": "^3.5.6"`
`"apollo3-cache-persist": "^0.13.0"`

**Comment by wodCZ** [comment]
I believe `apollo3-cache-persist` only highlights the issue from apollo-client that you've linked. This package doesn't modify the apollo client's options, it only binds itself to apollo-client's hooks and saves/restores the cache. This causes `fetchPolicy: cache-first` queries to never hit the network again, but ultimately the `fetchPolicy` is apollo-client's (or individual `useQuery` calls, as mentioned in the issue) responsibility.
