### ISSUE TITLE
undefined is not an object in Object.keys().reduce in persistanceMapper

### ISSUE THREAD

**Issue by raarts** [apollographql/apollo-cache-persist#457]
This happens because I don't have a mapped.ROOT_QUERY, but a mapped.ROOT_SUBSCRIPTION. So I changed:

```TypeScript
  mapped.ROOT_QUERY = Object.keys(rootQuery).reduce(
    (obj: any, key: string) => {
      if (key === '__typename') return obj;

```

into:

```TypeScript
  mapped.ROOT_QUERY = Object.keys(rootQuery || {}).reduce(
    (obj: any, key: string) => {
      if (key === '__typename') return obj;

```

But I have my doubts if this is the correct approach?

**Comment by wodCZ** [comment]
`persistenceMapper` is not an actual feature of this library and is provided only as a reference what could be achieved. As such, I'm not able to aid you much.

You can check with @KROSF who recently created a package based on the example. Here's their package: https://github.com/muchobien/apollo-persistence-mapper
