### ISSUE TITLE
feature request: publish the persistLink under react native example as a package

### ISSUE THREAD

**Issue by KROSF** [apollographql/apollo-cache-persist#459]
https://github.com/apollographql/apollo-cache-persist/tree/master/examples/react-native/src/utils/persistence

**Comment by KROSF** [comment]
I published one https://github.com/muchobien/apollo-persistence-mapper

**Comment by wodCZ** [comment]
Thanks for making a separate package for this. I'll close this since it can be achieved with your extension and doesn't need to be an actual feature of apollo3-cache-persist.

Feel free to add a link to your package to the linked example in a new PR.
