### ISSUE TITLE
Set storage instance variable on StorageWrappers to protected to enable inheritance

### ISSUE THREAD

**Issue by MasterOdin** [apollographql/apollo-cache-persist#464]
Right now, all of the wrappers under `src/storageWrappers` have `private storage` set for accessing the underlying storage engine. This makes it impossible to easily extend a given wrapper to add slight functionality as `this.storage` is not accessible. If it was instead `protected storage`, then the wrappers could be extended.

My use case is that I am using the `LocalForageWrapper` and want to replace the default JSON serialization with msgpack. My plan was to have something like the below:

```ts
import { decode, encode } from '@msgpack/msgpack';
import { LocalForageWrapper } from 'apollo3-cache-persist';

class CustomLocalForageWrapper extends LocalForageWrapper {
  getItem(key: string): Promise<object> {
    return this.storage.getItem(key).then((value) => decode(value));
  }

  setItem(key: string, value: string | object | null): Promise<void> {
    return new Promise((resolve, reject) => {
      this.storage
        .setItem(key, encode(value))
        .then(() => resolve())
        .catch(() => reject());
    });
  }
}
```

But I get TS errors with `Property 'storage' is private and only accessible within class 'LocalForageWrapper'.`. As such, I need to copy and paste the entire wrapper, which makes it more annoying to maintain, especially given the duplication of two methods and the interface over `storage`.

**Comment by wtrocki** [comment]
Sounds like trivial fix. Do you mind contributing that?
