### ISSUE TITLE
Does this library support @apollo/client@3.6.9 ?

### ISSUE THREAD

**Issue by roadmanfong** [apollographql/apollo-cache-persist#467]
I follow the document 
https://github.com/apollographql/apollo-cache-persist/blob/master/docs/faq.md#i-need-to-ensure-certain-data-is-not-persisted-how-do-I-filter-my-cache

I saw the storage persist the data I wanted.
Then I restart the app,   it shows restored the app, but it seems not working

```
[apollo-cache-persist] Restored cache of size 1467 characters
// I do some other query, not the filtered one
[apollo-cache-persist] Persisted cache of size 37 characters
```

**Comment by davidknezic** [comment]
Experiencing the exact same issue with `3.6.9`:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/198988/183645217-a085ecef-7ed9-411e-bd0b-1b6b60c73224.png">

**Comment by roadmanfong** [comment]
it turns out my code cause this
