### ISSUE TITLE
How to use with Angular/Ionic?

### ISSUE THREAD

**Issue by simonhaenisch** [apollographql/apollo-cache-persist#47]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

I'm trying to figure out how to use this with Angular/Ionic but can't seem to get it to work:

```ts
this.apollo.create({
	link: handleError.concat(auth).concat(link),
	cache: persistCache({
		cache: new InMemoryCache(),
		storage: localStorage,
	}),
});
```

```
Argument of type '{ link: ApolloLink; cache: Promise<void>; }' is not assignable to parameter of type 'ApolloClientOptions<{}>'.
  Types of property 'cache' are incompatible.
    Type 'Promise<void>' is not assignable to type 'ApolloCache<{}>'.
      Property 'read' is missing in type 'Promise<void>'.
```

Would also be nice if I could use `Storage` from `@ionic/storage` as the storage provider.

**Comment by jamesreggio** [comment]
Hi @simonhaenisch —

You're in luck. You _can_ use `@ionic/storage` as your storage provider! It appears to conforms to the very basic interface we require for storage providers, so just pass an instance of it as the `storage` key for `persistCache` and you should be good.

As for how to get it to work in general, you're 99% of the way there. The only problem in your code is that `persistCache` doesn't return a cache instance — it returns a promise that resolves when the cache has been restored. Here's how to fix it:

```js
const cache = new InMemoryCache();

// The await is optional, but you should use it if you want to guarantee that
// your cache has been restored before the rest of your app mounts.
await persistCache({
  cache,
  // You can keep using localStorage,
  // or pass an instance of the @ionic/storage provider here.
  storage: localStorage,
});

this.apollo.create({
  cache,
  link: handleError.concat(auth).concat(link),
});
```

Let us know if you have any other questions.

**Comment by simonhaenisch** [comment]
Thanks for the help, I still had errors though:

```
Argument of type '{ cache: InMemoryCache; storage: Storage; }' is not assignable to parameter of type 'ApolloPersistOptions<NormalizedCacheObject>'.
  Types of property 'storage' are incompatible.
    Type 'Storage' is not assignable to type 'PersistentStorage<PersistedData<NormalizedCacheObject>>'.
      Property 'getItem' is missing in type 'Storage'.
```

I was able fix it by setting the properties by hand:

```ts
await persistCache({
  cache,
  storage: {
    getItem: this.storage.get,
    setItem: this.storage.set,
    removeItem: this.storage.remove,
  }
});
```

**Comment by wtrocki** [comment]
IMHO Ionic is just simple wrapper for indexeddb. 
There are couple implementations available in npm that conform to cache-persist interface and support this out of the box:

https://www.npmjs.com/package/idb-localstorage (I'm maintained of that package)
I think that bringing indexeddb as default and the performant solution will help so many people that having issues with localforage that has some performance issues and it is not optimal for saving directly javascript objects.

**Comment by EricKit** [comment]
@simonhaenisch  How are you doing an asynchronous factory in the provider? Could you show the full module? I appreciate the help, I'ma tempting the same thing you are doing. I'm assuming this await is happening in factory below:

```
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink, Storage],
    },
  ],
```

**Comment by simonhaenisch** [comment]
This is from an old app prototype that I haven't worked on in 1.5 years... hopefully it helps, but please don't ask for more code, this is as much as I can share. Also, this might be quite outdated because Apollo/GraphQL has changed since then. I haven't worked with it since then, so I can't help you with questions about porting any of this either.

```ts
export class LoginPage {
  constructor(
    public storage: Storage,
    public apollo: Apollo,
    public httpLink: HttpLink,
    public toastCtrl: ToastController,
    public user: User,
  ) {
    // this gets updated in the app initializer, so it's reliable
    const isLoggedIn = this.user.isLoggedInSubject.value;

    if (!isLoggedIn) {
      this.shouldRender = true; // render the login form
      return;
    }

    // get token, then create apollo client and redirect to dashboard
    // (wrapped in async iife because constructors can't be async)
    (async () => {
      const token = await storage.get(STORAGE_KEYS.TOKEN);
      await this.createApolloClient(token);
      this.goToDashboard();
    })();
  }

  async createApolloClient(token: string) {
    const http = this.httpLink.create({ uri: config.api.graphqlUri });

    const ws = new WebSocketLink({
      uri: config.api.graphqlWebSocketUri,
      options: {
        reconnect: true,
        connectionParams: { token },
      },
    });

    const link = split(
      ({ query }) => {
        const def = getMainDefinition(query);
        return def.kind === 'OperationDefinition' && def.operation === 'subscription';
      },
      ws,
      http,
    );

    const auth = setContext((operation, prevContext) => ({
      headers: new HttpHeaders().set('Authorization', token ? `Bearer ${token}` : ''),
    }));

    const handleError = onError(({ graphQLErrors, networkError }) => {
      if (networkError) {
        if ((networkError as HttpErrorResponse).status === 401) {
          showErrorToast(this.toastCtrl, 'Your credentials are invalid. Please log in again.');
          setTimeout(() => this.user.logOut(), ms('3s'));
        } else {
          showErrorToast(this.toastCtrl, 'A network error occured. Please try again later.');
        }
      }

      if (graphQLErrors) {
        showErrorToast(this.toastCtrl, 'Request failed. Please try again later.');
      }
    });

    const cache = new InMemoryCache();

    await persistCache({
      cache,
      storage: {
        getItem: async key => this.storage.get(key),
        setItem: async (key, data) => this.storage.set(key, data),
        removeItem: async key => this.storage.remove(key),
      },
    });

    this.apollo.create({
      link: handleError.concat(auth).concat(link),
      cache,
    });
  }
```

**Comment by EricKit** [comment]
Thank you for your help.

**Comment by EricKit** [comment]
Thank you. To anyone else who lands here, this is what I did to keep it IAW the docs with the help of @simonhaenisch 

The problem is you want the call to be factory to be asynchronous, but you [can't do that](https://github.com/angular/angular/issues/23279). So I resolved the asynchronous code with `APP_INITIALIZER` which resolves all promises before continuing.

I turned my the logic into a service (not required, just too much going on in my module). Basically the service has two functions. One that does asynchronous work and sets a local variable called options. Another function which reads options.

Below is the module. Note that the APP_INITIALIZER will wait for all promises to be resolved before it continues. This is where all the async code goes to await the persistCache. After the promises are resolved, and the ApolloClientService has the options set, then the apolloClientService.getOptions() will return synchronously.

```
export function resolveApolloClientOptions(apolloClientService: ApolloClientService) {
  return () => apolloClientService.getOptionsPromise();
}

export function apolloClientServiceFactory(apolloClientService: ApolloClientService) {
  return apolloClientService.getOptions();
}

@NgModule({
  exports: [ApolloModule, HttpLinkModule],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: resolveApolloClientOptions,
      deps: [ApolloClientService],
      multi: true,
    },
    ApolloClientService,
    {
      provide: APOLLO_OPTIONS,
      useFactory: apolloClientServiceFactory,
      deps: [ApolloClientService, APP_INITIALIZER],
    },
  ],
})
export class GraphQLModul
```

The final version of my persistCache looks like

```
    await persistCache({
      cache,
      storage: {
        getItem: key => this.storage.get(key),
        setItem: (key, data) => this.storage.set(key, data),
        removeItem: key => this.storage.remove(key),
      },
    });
```
