### ISSUE TITLE
Prevent user to close browser tab when there is pending writes

### ISSUE THREAD

**Issue by lbdremy** [apollographql/apollo-cache-persist#470]
Hello,
Thanks for the work on this module that's really useful !

I would like to implement some logic to prevent/alert a user who is closing the browser tab if there is still pending writes due to the debounce mechanism or the async operation to persist the cache.

I read about it in an old issue https://github.com/apollographql/apollo-cache-persist/issues/1#issuecomment-348980884, it was an option to use the onbeforeload event and so alert the user if required. From the API available I'm not sure how can I know if a write is pending, at the moment it seems I can only lower the debounce interval still it won't display an alert if the async operation to persist the cache is ongoing. I will be happy to contribute, just point me to the right direction 😀 .  

Thanks for your help 🙏 !

**Comment by lbdremy** [comment]
Hello [@wtrocki](https://github.com/wtrocki), [@wodCZ](https://github.com/wodCZ), [@jspizziri](https://github.com/jspizziri) 👋 

I'm wondering if you had a chance to take a look at this issue, I know the holidays went by there or at least I hope for you 🌞 🗻 🏖️ ,  if anything is missing in my explanations I would love to add what is missing. 

Thanks a lot for your help 🙏

**Comment by wodCZ** [comment]
Hi @lbdremy 👋 

From a quick look at the API I guess you could access the public attributes down to `persistorInstance.trigger.timeout`, which is non-null when there's a pending write: https://github.com/apollographql/apollo-cache-persist/blob/d536c741d1f2828a0ef9abda343a9186dd8dbff2/src/Trigger.ts#L81-L85

A naive implementation could then look like this (untested):
```js
addEventListener('beforeunload', function(event) {
    if (persistor.trigger.debounce && persistor.trigger.timeout) {
        event.preventDefault();
        persistor.persist(); // forcefully persist, skipping the trigger mechanism
        event.returnValue = 'Some actions have not been saved. Are you sure you want to leave?';
    }
});
```

The user experience will suffer though, especially if there are periodic queries which trigger the debounce period without user's interaction. Not to mention the [reliability issues](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#usage_notes).

**Comment by lbdremy** [comment]
Thank you @wodCZ for your answer :)  Indeed the periodic queries are quite problematic, plus the reliability issues, plus the documentation you're pointing at mention the fact `beforeunload` event should be setup [only when there is unsaved changes and remove after](https://developer.chrome.com/blog/page-lifecycle-api/#the-beforeunload-event), because when present it prevents browsers from caching the page in their [Back-Forward Cache](https://developer.chrome.com/blog/page-lifecycle-api/#back-forward-cache).
According to the Page Lifecycle documentation it seems the `Hidden` state is right place to perform persistance task (https://developer.chrome.com/blog/page-lifecycle-api/#developer-recommendations-for-each-state). I think I'm going to listen for the `Hidden` state and perform `persistor.persist()` here using the page lifecycle lib https://github.com/GoogleChromeLabs/page-lifecycle. I will keep you posted with the result.

**Comment by lbdremy** [comment]
Hi @wodCZ , to keep you posted, I ended up using the `visibilitychange` event and `pagehide` event to persist the cache before the tab is closed, it also persists the cache when switching tab but that's not an issue, the code looks like that:

```
/**
     * @note objective is to persist cache currently in memory into localstorage before the tab is closed
     * visibilitychange event is the last reliable event dispatched when an user closes the tab
     * see https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event#usage_notes
     * except on previous Safari/iOS versions (the issues mentionned in mdn are fixed since end of 2020 but mdn is outdated.)
     * when navigating away from a document, instead pagehide is used for this case
     * see https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event#browser_compatibility
     * a comprehensive view of the page lifecycle is available at https://developer.chrome.com/blog/page-lifecycle-api/#developer-recommendations-for-each-state
     * they offer a library which encapsulates that logic but not maintained, no TS types and error at runtime...
     **/
    document.addEventListener(
      'visibilitychange',
      () => {
        if (document.visibilityState === 'hidden') {
          persistor?.persist()
        }
      },
      { capture: true }
    )
    document.addEventListener(
      'pagehide',
      () => {
        persistor?.persist()
      },
      { capture: true }
    )
```
