### ISSUE TITLE
Lazy loading cache

### ISSUE THREAD

**Issue by simplenotezy** [apollographql/apollo-cache-persist#479]
I am looking for a way to use the data from cache if available, but always re-run the query to fetch fresh data. Is this possible? Not apparent from reading the docs.

**Comment by wodCZ** [comment]
@simplenotezy sorry for the late response.

See [fetch policy documentation](https://www.apollographql.com/docs/react/data/queries#setting-a-fetch-policy) for how to modify cache behaviour. `cache-and-network` policy should be the one you're looking for.
