### ISSUE TITLE
Unneeded persistence of network-only queries

### ISSUE THREAD

**Issue by mefjuu** [apollographql/apollo-cache-persist#48]
In my opinion, queries with cache policy set to 'network-only' oughtn't to be persistent. 
CachePersistor seems not to respect this policy and store all the queries.

**Comment by jamesreggio** [comment]
Hi @mefjuu —

This is a limitation with how `apollo-cache-inmemory` is built. The cache reconstructs the results of _every_ query every time _any_ query is fetched, and thus it needs to temporarily cache the results of `network-only` queries to be able to reconstruct their results as needed.

`apollo-cache-persist` is fairly dumb and just dumps + restores the entire contents of the cache. Right now, there's no way to tag chunks of data within the cache with different persistence policies, but it's definitely something that the Apollo team has in mind for v3.

There's been a long discussion about cache filtering in #2, so I'm going to close this issue for now and we can continue to track it over there.

Thanks for sharing your opinion!
