### ISSUE TITLE
Smarter purging

### ISSUE THREAD

**Issue by danieljvdm** [apollographql/apollo-cache-persist#49]
As far as I understand, we purge the cache once it reaches a certain size. Is there possibly a more intelligent way to do this? E.g. trim older queries, or is that impossible?

**Comment by danieljvdm** [comment]
I've kind of answered my own question by looking deeper into the cache, which seems to just be a simple key/value store of query names to their results so there isn't much information to work with here. 

A crude solution I can think of would be using some kind of FIFO collection and dequeuing it once it reached the max size.

**Comment by jamesreggio** [comment]
Have a look at #2, where we discussed this idea.

The short summary is that the current APIs exposed by the cache itself are very basic. There are only two operations: extract the entire cache as an opaque blob, and restore the entire cache as an opaque blob.

More sophisticated purging would require, at minimum, storing additional metadata on individual cache entires (such as the last-fetched or last-accessed timestamps), which isn't supported — and it would require the ability to selectively extract/restore data.

If you wanted to hack something together, you could make some assumptions about the shape of the blob that comes out of the cache `extract` method, but those assumptions would be fragile and not portable to other caches.
