### ISSUE TITLE
Why was the persistLink and persistenceMapper example removed?

### ISSUE THREAD

**Issue by guso1330** [apollographql/apollo-cache-persist#490]
The persistLink example within the react native example project was removed recently.

What was the motivation behind this and are there some underlying issues with using the directive based approach?

With our current MFE project structure we have it setup so that each individual MFE needs to opt into using the persistent cache. Having a directive mechanism would allow each to manage what would be cached versus just everything.

Any chance an example for the persistLink could be re-added?

**Comment by wodCZ** [comment]
Hello @guso1330,

the motivation behind removing react native example along with the persistenceMapper and persist link example was that most of the maintainers of this repository have already moved to different stacks, so the amount of support and work we can do here is greatly limited. We're trying to at least keep up with the security updates, and react native was too big of a burden to keep up to date.

> are there some underlying issues with using the directive based approach?

None that I'm aware of. Nothing in the library was changed during my recent cleanup, and if it was working for you before, it still will.

Please feel free to create a PR that re-adds the custom link/mapper examples again, within the web example. Here's the link to a commit before they were removed: https://github.com/apollographql/apollo-cache-persist/tree/a0b45608ffe501c50fc34e2968fd53962fb27ce6/examples/react-native/src

**Comment by guso1330** [comment]
Appreciate the quick response!

Our app isn't react-native either, so that wasn't the concern as much as wondering if there was some underlying issue with that approach.

Will take a look at the commit and see if anything shareable comes out of our work we do implementing it. Thanks!
