### ISSUE TITLE
[Request] - Please update code for MMKVStorage instance creation as per their new implementation

### ISSUE THREAD

**Issue by vaibhav-toddleapp** [apollographql/apollo-cache-persist#499]
Hey! according to documentation of MMKVStorage, instance creation has slightly different approach. see the below link and update the documentation code. ( if you feel it is helpful then only 🙃 )

https://rnmmkv.vercel.app/#/creatinginstance

Example:
```javascript

import { MMKVLoader } from "react-native-mmkv-storage";

const MMKVwithID = new MMKVLoader()
  .withInstanceID("mmkvWithID")
  .initialize();
```

**Comment by ansmlc** [comment]
Did you figure out how to do this with apollo-cache-persist?

/**
 * Wrapper for react-native-mmkv-storage.
 * See [https://rnmmkv.now.sh/#/gettingstarted](https://rnmmkv.now.sh/#/gettingstarted) for installation instructions.
 *
 * @example
 * const persistor = new CachePersistor({
 *   cache,
 *   storage: new MMKVStorageWrapper(new MMKVStorage.Loader().initialize()),
 * });
 *
 */
