### ISSUE TITLE
AsyncStorageWrapper cache data missing / disappearing

### ISSUE THREAD

**Issue by PeterKucera** [apollographql/apollo-cache-persist#533]
Hey folks

I'll just leave this as a note here - I was running into issue where Apollo Cache was being deleted, and I couldn't figure out what's causing this. 

Looks like root cause for this issue was that when you call a `persistCache()` method,  initial cache size is set to 1MB, and if your cache exceeds this amount, cache will be overridden / purged.

Solution is to set `persistCache()` `maxSize` arg to a large number (or ideally to `false`), so there won't be any limit on the cache size, and therefore it won't get purged when it gets full.

https://github.com/apollographql/apollo-cache-persist/blob/master/docs/advanced-usage.md

![image](https://github.com/user-attachments/assets/e354c670-6ed7-498e-b317-6236a6220cdd)

**Comment by diego-betto** [comment]
Thank you @PeterKucera, you saved my day :)
