### ISSUE TITLE
No persistence when app closes

### ISSUE THREAD

**Issue by joshg111** [apollographql/apollo-cache-persist#54]
I first check the cache, then write to the cache, then check the cache again. The first time I check the cache I expect null, then after I expect 'abc'. When I close and reopen the app I expect the first cache check to be hydrated showing 'abc', but again I get null again. 

```javascript
import React from 'react';
import { AsyncStorage, ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { ApolloProvider, Mutation, Query, withApollo } from "react-apollo";
import ApolloClient from "apollo-boost";
import gql from "graphql-tag";
import { persistCache } from 'apollo-cache-persist';
import { InMemoryCache } from 'apollo-cache-inmemory';


const cache = new InMemoryCache();

persistCache({
  cache,
  storage: AsyncStorage,
});

const defaults = {
  currentUser: null
}

const typeDefs = `
type Query {
  currentUser: String
}
`;

const client = new ApolloClient({
  cache,
  uri: "https://us1.prisma.sh/jagreenf111-8fe67d/prisma-liveqa/dev",
  clientState: {
    defaults,
    typeDefs
  }
});

const GET_USER = gql`
{
  currentUser @client
}
`;

client.query({query: GET_USER}).then((data)=>{
  console.log("before: ", data);
});
client.writeData({data: {currentUser: "abc"}});
client.query({query: GET_USER}).then((data)=>{
  console.log("after: ", data);
});
```

**Comment by jamesreggio** [comment]
Cache restoration is asynchronous, so you're probably querying the cache before it's been restored.

You can verify this by adding `debug: true` to the options passed to `persistCache`, which will cause the cache to log when it's been restored. You'll probably see that logging happen after your `before: ` logline.

I've added some example code for how to wait for the cache to be restored before rendering your app, which you can review here: https://github.com/apollographql/apollo-cache-persist#react

If you have further issues, please let me know and we'll reopen this.
