### ISSUE TITLE
Add peerDependency for localForage 

### ISSUE THREAD

**Issue by santiagoecheverri94** [apollographql/apollo-cache-persist#57]
Hi! I am using _apollo-cache-persist_ with TypeScript and [localForage](https://github.com/localForage/localForage). 

_apollo-client-persist_ with TypeScript seems to be incompatible with [localForage](https://github.com/localForage/localForage) version 1.60 and on because _localForage_ changed its signature of the `setItem` method in version 1.6.0

The [`setItem method`](https://github.com/apollographql/apollo-cache-persist/blob/master/src/types/index.ts#L15) signature looks as follows in _apollo-client-persist_:

`setItem: (key: string, data: T) => Promise<void> | void;`

In _localForage pre 1.6.0_, the [`setItem method`](https://github.com/localForage/localForage/blob/1.5.7/typings/localforage.d.ts#L21) used to look like this:

`setItem<T>(key: string, value: T, callback: (err: any, value: T) => void): void;`

So, obviously, they were compatible. However, in _localForage post 1.6.0_, the [`setItem method`](https://github.com/localForage/localForage/blob/1.6.0/typings/localforage.d.ts#L20) now looks like this:

`setItem<T>(key: string, value: T, callback?: (err: any, value: T) => void): Promise<T>;`

Which, is incompatible because _apollo-client-persist_ expects the `setItem method` to return either `Promise<void>` OR `void`, yet since version 1.6.0 _localForage_ now returns `Promise<T>`

We as users of _apollo-client-persist_ could be easily warned about this through the`"peerDependencies"` field within the _apollo-client-persist_ `package.json`. Or, maybe `apollo-client-persist` could be upgraded to also accept `Promise<T>`?

On a side note, I realize this is only a problem if using TypeScript, like I am, since this would be no problem at all with JavaScript. This is actually the first time I ever find a benefit of using JavaScript over TypeScript.

**Comment by jamesreggio** [comment]
This should be fixed by #58.

**Comment by santiagoecheverri94** [comment]
Thank you @jamesreggio

**Comment by wtrocki** [comment]
Resolved and merged
