### ISSUE TITLE
Confused on how the cache is supposed to work

### ISSUE THREAD

**Issue by vinceprofeta** [apollographql/apollo-cache-persist#60]
Hey there having an issue with apollo-boost and react native regarding local state. If i set local state for geo points and using react navigation I transition to another page the geo points are then set back to the defaults?

If i dont set defaults they dont reset but I get yellow box errors. Any ideas?

This library solves that issue, but do I need to use this library to solve it?

**Comment by wtrocki** [comment]
The short answer is yes this is needed because how react native routing works.
