### ISSUE TITLE
Cache is not invalidated based on @cacheControl ?

### ISSUE THREAD

**Issue by DanielHoffmann** [apollographql/apollo-cache-persist#67]
So checking the localstorage state I noticed that there are no timestamps or cache-control information in the cache at all. It seems like apollo-client cache is not aware of this information and is not properly invalidating data based on how old it is.

I also noticed that even if I set `fetchPolicy="no-cache"` in `Query` the component will still render with the cached data before making the request and showing the new data. It is arguable if this is good behaviour or not, but I believe if the data is stale it should not be shown.

This is not that big of an issue for InMemoryCache as it is cleared when you reload the page, but if you persist the cache is completely breaks the page for users after a period.

**Comment by jamesreggio** [comment]
Hi @DanielHoffmann —

Unfortunately, the `@cacheControl` directive has no relationship to any of Apollo's client-side components. It's used strictly by the caching infrastructure within Apollo Engine (which is used primarily to reduce load on your API's data sources).

On the other hand, `fetchPolicy="no-cache"` should not be behaving that way. Regardless of whether you're using `apollo-cache-persist`, it should never show data that hasn't been immediately fetched from the network. This, however, is a problem with `apollo-client` itself, so it'd be better for you to file that bug over on that repo.
