### ISSUE TITLE
ApolloClient client.clearStore() causing localStorage to be === '{}'

### ISSUE THREAD

**Issue by frederikhors** [apollographql/apollo-cache-persist#68]
In my `logout` route I'm using the new `client.clearStore()` instead of `resetStore()`.

I'm also using `window.localStorage` as `apollo-cache-persist` storage.

When I call `clearStore()` it set `localStorage['my-storage-key']` to: `{}`.

This is a problem for many things, for example for the `apollo-link-state` `defaults` resolvers.

In this case is it better to delete or set to empty value the `localStorage` storage?

**Comment by wtrocki** [comment]
Purge operation will clear the key. https://github.com/apollographql/apollo-cache-persist/blob/master/src/Storage.ts#L27

However empty object in cache going to be saved again. Persist operation can actually check for number of keys on Object and do not persist an empty one but first I would like to know exact bugs that this is causing

**Comment by frederikhors** [comment]
@wtrocki today the situation is https://github.com/apollographql/apollo-cache-persist/issues/126.

Maybe something has changed since this issue was opened?

**Comment by wtrocki** [comment]
We have released apollo-cache-persist-dev package that has some changes.

**Comment by wtrocki** [comment]
Proper approach will be to use purge that will remove cache
