### ISSUE TITLE
Chrome Extension support

### ISSUE THREAD

**Issue by dcosson** [apollographql/apollo-cache-persist#70]
It would be useful to be able to use chrome extension persistence with this library. I would think this should be pretty easy because the API of `chrome.storage` is the same as `window.localStorage`. Is that something that could be supported?

**Comment by jamesreggio** [comment]
If `chrome.storage` has the exact same API as `window.localStorage`, then just pass it in as the value for `storage` and it should just work.

The storage provider is meant to be pluggable, and any object that supports `setItem(key, value) -> Promise | void`, `getItem(key) -> Promise | string`, and `removeItem(key) -> Promise | void` will 'just work'.
