### ISSUE TITLE
persistCache maxSize seems to default to false

### ISSUE THREAD

**Issue by mcbroh** [apollographql/apollo-cache-persist#72]
While using persistCache and local storage with angular apollo, we get chrome error for local storage maxSize exceeded without setting maxSize to false. Tried setting maxSize to different values but  the persistCache debug shows that its caching more than values set.  Even at that when chache value reaches about 5mb chrome throw error. Any help or explanation will be happily welcome.

**Comment by pl12133** [comment]
Hard to debug without the exact error message, can you paste the error here?

I'm not sure if you are talking about an error being thrown by the `apollo-cache-persist` library or a [`QuoteExceededError`](https://developer.mozilla.org/en-US/docs/Web/API/DOMException#exception-QuotaExceededError).

**Comment by wtrocki** [comment]
There will be two factors here. If cache is saving objects instead of strings maxSize is going to be ignored. Chrome localstorage in Webview on IOS/Android will limit single key to max 5mb. 

Is that using localStorage as store?

**Comment by wtrocki** [comment]
I cannot replicate this issue
