### ISSUE TITLE
Cache is not persisted on refresh with apollo-boost

### ISSUE THREAD

**Issue by maamounapprise** [apollographql/apollo-cache-persist#73]
Issue: 
Cache is not persisted on refresh, I am not sure what I am doing wrong. 

This is my app.js, I am using apollo-boost 

```
class App extends Component {
  state = {
    client: null,
    loaded: false
  };

  async componentDidMount () {
    const cache = new InMemoryCache()

    await persistCache({
      cache,
      storage: window.localStorage
    })
    const client = new ApolloClient({
      cache,
      uri: 'http://localhost:8080/graphql',
      clientState: {
        defaults,
        resolvers
      }
    })

    this.setState({
      client,
      loaded: true
    })
  }

  render () {
    const { client, loaded } = this.state
    if (!loaded) {
      return <div>Loading...</div>
    }

    return (
      <ApolloProvider client={client}>
        <Router>
          <Switch>
            <Route path='/' exact component={Application} />
            <Route path='/set-registration-state' exact component={SetRegistrationTypes} />
          </Switch>
        </Router>
      </ApolloProvider>
    )
  }
}

ReactDOM.render(<App />, document.getElementById('root'))
registerServiceWorker()

```

**Comment by maamounapprise** [comment]
I fixed it with apollo client, but this is a serious issue at least update the documentation and let us know that it doesn't function with apollo boost.

**Comment by codingwaysarg** [comment]
Hi! How do you fix it?

**Comment by codingwaysarg** [comment]
> I fixed it with apollo client, but this is a serious issue at least update the documentation and let us know that it doesn't function with apollo boost.

Can you show the fix pls?

**Comment by Abenezer** [comment]
@maamounapprise i have same problem .. digging further 
when using Apolo-Boost the cache is already there ... (if you log client from  {data, client, error}.. of <Query> component ) and  manually firing client.query(...) works as expected . the <Query> component is not reading the provided cache ... 
what do you think?

**Comment by Abenezer** [comment]
it now working
in my case it was because the cache is passed to client before persistCache completes (i didnt add async there) .. but i don't know why @maamounapprise first post is not working. (i copy paste it and its loading from cache after refresh as expected)

**Comment by melo0187** [comment]
I can confirm that calling `persistCache` before calling ReactDOM's `render` with ApolloProvider does finally showcase the expected behavior, which is the absence of further POST requests to your GraphQL API on page refreshes.

Thanks to @maamounapprise and @Abenezer for the explanations provided in this issue. This made it much easier to figure out what is going on.

However now I think that using apollo-boost with react-apollo is somehow pointless considering the fact that I have to import apollo-cache-persist, apollo-link, apollo-link-http and apollo-link-state to be able to wait for the client cache to be ready before actually rendering the React app. :disappointed: 

This is the shortest version I came up with (based on the basic example from the book "Learning GraphQL":
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { ApolloProvider } from 'react-apollo'
import { ApolloClient, InMemoryCache } from 'apollo-boost'
import { persistCache } from 'apollo-cache-persist'
import { ApolloLink } from 'apollo-link'
import { withClientState } from 'apollo-link-state'
import { HttpLink } from 'apollo-link-http'

const serverUri = 'http://localhost:4000/graphql'

const cache = new InMemoryCache()
const stateLink = withClientState({
  cache
})
const httpLink = new HttpLink({ uri: serverUri })

const client = new ApolloClient({
  cache: cache,
  link: ApolloLink.from([
    stateLink, httpLink
  ])
})

const setupAndRender = async () => {
  await persistCache({
    cache,
    storage: window.localStorage
  })
  ReactDOM.render(
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>,
    document.getElementById('root')
  )
}

setupAndRender()
```

**Comment by melo0187** [comment]
Actually I have to take this back... =)

You can still use apollo-boost and ONLY add apollo-cache-persist for things to work as expected.
That could look like this:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { ApolloProvider } from 'react-apollo'
import ApolloClient, { InMemoryCache } from 'apollo-boost'
import { persistCache } from 'apollo-cache-persist'

const cache = new InMemoryCache()
const client = new ApolloClient({
  cache: cache,
  uri: 'http://localhost:4000/graphql'
})

const setupAndRender = async () => {
  await persistCache({
    cache,
    storage: localStorage
  })
  ReactDOM.render(
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>,
    document.getElementById('root')
  )
}

setupAndRender()
```

Furthermore I learned that my expectation was wrong. Without apollo-cache-persist there is no reason to expect the cache to be present on a page reload... my bad.

**Comment by wtrocki** [comment]
Looks like issue is fixed. Thanks for update.

**Comment by Rahul-PM** [comment]
[https://stackoverflow.com/a/65507044/14913151]
This solution worked for me..
It was cache exceeding the limit of 1MB set by apollo-cache-persist
