### ISSUE TITLE
Incompatible with withClientState defaults

### ISSUE THREAD

**Issue by bechtold** [apollographql/apollo-cache-persist#79]
Hi,
I set Apollo up like this (Angular project):

`@NgModule({
  imports: [HttpClientModule, ApolloModule],
  providers: [{
    provide: APOLLO_OPTIONS,
    useFactory() {
      const cache = new InMemoryCache();

      persistCache({
        cache,
        storage: window.localStorage
      });

      return {
        link: withClientState({
          cache,
          resolvers,
          defaults,
          typeDefs
        }),
        cache
      };
    }
  }]
})`

where defaults looks like this:
`export const defaults = {
  todos: [],
  visibilityFilter: 'SHOW_ALL',
  counterValue: 0,
};`

Now when I start up my app the counterValue is always 0, taken from the defaults.
But if 7 is stored in the localStorage the 0 would be wrong.
As soon as I mutate the value it actually loads the value from localStorage. So let's say I add 1 to the counterValue it actually returns as 8.
This can be fixed by removing the defaults, but what if I want defaults?
I would assume that the values form defaults are taken when there is nothing in the localStorage and otherwise the localStorage value are taken.

Here is a stackblitz that I use as a playground where I found this behavior.
https://stackblitz.com/edit/apollo-angular-local-state-counter?file=src%2Fapp%2Fgraphql%2Fgraphql.module.ts

**Comment by tamm** [comment]
This issue had me so confused for so long!

My initial problem was a race condition where some of my components would get the correct persisted value but some would get the default and then not get updated until I changed something in the store which then shook the persisted value into place.

What's wrong? cachePersist is _asynchronous_ and it isn't clearly defined how to handle this. 

I found the solution in my Vue project was to make sure everything intialised in the correct order.
Posting this here to help anyone who finds it from google.

Maybe the documentation could be updated to reflect this type of implementation?

main.js
```
import Vue from "vue";
import App from "./App.vue";
import router from "./router";

import { createProvider } from "./vue-apollo";

// we wait for the apollo provider to be done in order to
// not initialise before the cache has been read from localstorage
createProvider().then((apolloProvider) => {
  new Vue({
    router,
    apolloProvider,
    render: h => h(App)
  }).$mount("#app");
});
```

vue-apollo.js
```
import Vue from "vue";
import VueApollo from "vue-apollo";
import {
  createApolloClient,
  restartWebsockets
} from "vue-cli-plugin-apollo/graphql-client";
import { localResolvers, localDefaults } from "./vue-apollo-local";
import gql from "graphql-tag";
import { InMemoryCache } from "apollo-cache-inmemory";
import { persistCache } from "apollo-cache-persist";
import { withClientState } from 'apollo-link-state';

const persistedCache = new InMemoryCache();

// Install the vue plugin
Vue.use(VueApollo);

// Call this in the Vue app file
export async function createProvider (options = {}) {
  // Set up Apollo Link State
  const stateLink = withClientState({
    cache: persistedCache,
    defaults: localDefaults,
    resolvers: localResolvers
  });

  // Set up Apollo Cache Persist, and wait for it to finish
  await persistCache({ cache: persistedCache, storage: window.localStorage }).then(()=>{console.log('done persist');});

  // Create apollo client
  const { apolloClient, wsClient } = createApolloClient({
    ...defaultOptions,
    ...options,
    cache: persistedCache,
    link: stateLink
  });
  apolloClient.wsClient = wsClient;

  // Create vue apollo provider
  const apolloProvider = new VueApollo({
    clients: {
      default: apolloClient
    },
    defaultClient: apolloClient,
    defaultOptions: {
      $query: {
        // fetchPolicy: 'cache-and-network',
      }
    },
    errorHandler(error) {
      // eslint-disable-next-line no-console
      console.log(
        "%cError",
        "background: red; color: white; padding: 2px 4px; border-radius: 3px; font-weight: bold;",
        error.message
      );
    }
  });

  return apolloProvider;
}
```

I'm not claiming this is the most elegant way to do this, but it does give me proper cache restore on page reload.

**Comment by tamm** [comment]
This is also related to #61 and #59

**Comment by wtrocki** [comment]
Apollo link state is embedded into Apollo 2.5. persist operation will require async await. 

I think we can document how to do await effectively for different frameworks like Vue React etc. WDYT?

**Comment by bechtold** [comment]
I updated my stackblitz to use Apollo 2.5:
https://stackblitz.com/edit/angular-local-state-apollo-updated?file=src/app/graphql/graphql.module.ts
still the same issue.
I'm no expert on async await yet, so help would be appreciated.

It looks like I can't make the factory function asynchronous, so I guess as @tamm pointed out the only way is to create Apollo and it's persisted caching before bootstrapping angular (in my case). That does not sound like it's a good way todo imho.
Wouldn't a synchronous persistCache function maybe make sense here? Does that exist at?
I guess another way would be not to use defaults at all and just provide them where the queries are called, but that doesn't seem like a good idea either.

**Comment by wtrocki** [comment]
What I hear is that synchronous method as alternative would be benefitial for community. It has many disadvantages but that depends on use case. Example app that creates client and awaits (uses root module) 

https://github.com/aerogear/ionic-showcase/blob/master/src/app/services/sync/voyager.service.ts#L50

**Comment by wtrocki** [comment]
We have added async api in dev package.
