### ISSUE TITLE
compression support?

### ISSUE THREAD

**Issue by zsolt-dev** [apollographql/apollo-cache-persist#81]
Hi,

Safari mobile has a 5MB limit for localstorage and I need slightly more, since I am implementing offline first strategy.

Compression would allow me to do that. 

1. Is compression the right way to go?
2. if yes, what would be a good way to implement compression? 

Thank you

**Comment by pl12133** [comment]
Using compression can give you more space but also consumes more CPU, that's the trade-off of compression. You can try a compression library from `npm` to see if the performance overhead is worth the additional space.

An alternative way to get more space is by using `IndexedDB`. We are wrapping [`idb-keyval`](https://github.com/jakearchibald/idb-keyval) into a `StorageProvider`:

```js
import { get, set, keys, del, clear } from 'idb-keyval';

export default {
  clear() {
    return clear();
  },
  getItem(key) {
    return get(key);
  },
  setItem(key, value) {
    return set(key, value);
  },
  keys() {
    return keys();
  },
  remove(key) {
    return del(key);
  },
  removeItem(key) {
    return del(key);
  }
};
```

**Comment by zsolt-dev** [comment]
Thank you for this.

I switched to localForage, but it was huge (30kB) and your solution is much more lightweight and works great!

**Comment by charpeni** [comment]
I ended up building a wrapper around `localForage`, but with compression: https://github.com/charpeni/apollo-cache-persist-compressed.
