### ISSUE TITLE
defaultState overrides persisted cache

### ISSUE THREAD

**Issue by serranoarevalo** [apollographql/apollo-cache-persist#85]
Hello!
So I have this code on an async function before I set up my apollo provider in React.

![code](https://user-images.githubusercontent.com/3612017/52173255-82f81080-2746-11e9-9347-5a841dd8ab6b.png)

And I have some defaultState

![code](https://user-images.githubusercontent.com/3612017/52173257-a327cf80-2746-11e9-9255-5d5ef6e3fc9e.png)

Later I'm firing a mutation that sets ```isLoggedIn``` to ```true```

The problem is that when I refresh the defaults always take over an even after the cache is restored ```isLoggedIn``` will always be ```false```

Am I doing something wrong or is there any workaround to be able to use defaultState and apollo-cache-persit?

**Comment by serranoarevalo** [comment]
😭

**Comment by perminder-klair** [comment]
same issue guys. any solution?

**Comment by serranoarevalo** [comment]
@perminder-klair  I ended up loading and saving the defaults from/to AsyncStorage

**Comment by perminder-klair** [comment]
@serranoarevalo thanks! I did with this hacky way:
```
 withClientState({
      resolvers,
      cache,
      defaults: window.localStorage.length === 0 ? defaults : {},
      typeDefs
    })
```

**Comment by sylvainbaronnet** [comment]
same issue

**Comment by cometkim** [comment]
I think this should be fixed by apollo-client side https://github.com/apollographql/apollo-client/blob/4c017c8e8bae727d2f33db02d3c5e2592e2fd00e/packages/apollo-boost/src/index.ts#L179-L184

**Comment by wtrocki** [comment]
Resolved in apollo cache
