### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by ajhool** [apollographql/apollo-cache-persist#86]
This package is recommended in the official Apollo GraphQL Getting Started guide but doesn't seem to be maintained. Is this repository dead?

This typescript compile-breaking issue was reported in Jun '18 ( #55 ), was fixed in Jul '18 #58 , but the PR hasn't gone through, yet. The last code commit to master was a year ago

**Comment by sylvainbaronnet** [comment]
Looks like it is... Anyone willing to create an "official" fork ?

**Comment by ajhool** [comment]
@sylvainbaronnet I can create the fork this week

**Comment by wtrocki** [comment]
I'm acually working on improving Apollo-cache-persist:

- by adding garbage collector on restarts
- optional storage for optimistic responses
- performance tweeks (data spread)

The fork is here: https://github.com/graphql-heroes/apollo-cache-persist
I'm happy to accept any PR's or other improvements.

**Comment by Hasan-git** [comment]
@wtrocki 
how can I install it in my project ?

**Comment by wtrocki** [comment]
Just swap original library like bellow:
```
npm uninstall apollo-cache-persist
npm install @graphqlheroes/apollo-cache-persist
```

The published version has all types fixed.

**Comment by wtrocki** [comment]
I'm hoping to do a little bit of maintenance of the project now. If you have any urgent issues please ping me directly on the issue.

**Comment by wtrocki** [comment]
I have created roadmap issue and merged all outstanding PR's. Closing issue as repo is def not dead anymore ;)

**Comment by ajhool** [comment]
Thank you! It's much appreciated.

**Comment by Hasan-git** [comment]
Thank you @wtrocki 
Great job

**Comment by Hasan-git** [comment]
> Just swap original library like below:
> 
> ```
> npm uninstall apollo-cache-persist
> npm install @graphqlheroes/apollo-cache-persist
> ```
> 
> The published version has all types fixed.

@wtrocki its no required to switch to @graphqlheroes/apollo-cache-persist anymore ?

**Comment by wtrocki** [comment]
This repository will not be released as frequently. I'm working now on enabling github installation from this repo and getitng npm rights to release it but it will take while. Till then feel free to use `@graphqlheroes/apollo-cache-persist` that has all the changes that were blocking community.

**Comment by wtrocki** [comment]
YOu can watch for releases on this repository to get informed.

**Comment by lookfirst** [comment]
Seems dead again. lol

**Comment by wtrocki** [comment]
@lookfirst Do you have any specific issue that you work on. 
There is a huge release of apollo clinet coming soon that will have some persistence included.

**Comment by lookfirst** [comment]
No specific issue, yet. Just started using it. But seems like since this project and your other project haven't had any updates.... .... ....

**Comment by reinvanimschoot** [comment]
So what should we be using right now?
@graphqlheroes/apollo-cache-persist or just apollo-cache-persist?

Also, I'm still getting typescript issues when using localstorage as storage. Not sure if this was supposed to be fixed or not?

Thanks!

**Comment by lookfirst** [comment]
I'm just using a-c-p (without the @).

The localstorage is easily worked around... 

```
	await persistCache({
		cache,
		storage: window.localStorage as any,
	});
```
