### ISSUE TITLE
Allow delaying cache-first queries until cache is restored

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-cache-persist#88]
If we want to wait to render the entire app until after the cache is restored, we use the method [in the readme](https://github.com/apollographql/apollo-cache-persist#how-do-i-wait-for-the-cache-to-be-restored-before-rendering-my-app). But if we want to render the app into a loading state (ie each component receiving `loading` from each query) and not have the app send `cache-first` queries to the server, I think the easiest way for that to happen would be for apollo client to do something like:

```js
if (persistCachePromise) {
  if (persistCachePromiseIsPending) {
    // give `loading` to components
  } else {
    // perform `cache-first` queries (and most/all will not hit the network)
  }
} else {
  // there's no persistence—act normal
}
```

Ideally it could know which queries would be available when the cache was restored, so that it doesn't delay sending the queries it knows won't hit the cache.

**Comment by wtrocki** [comment]
We provide now async api. Alternatively loading screen can be added

**Comment by lorensr** [comment]
@wtrocki I think you may be misunderstanding this feature request? The feature is unable to be implemented with the async API described in the README. Lmk if there's a specific part of this FR that you have a question about.

**Comment by wtrocki** [comment]
Typo on my side. I meant sync api. There are also some suggestions here that cannot be done in lib as they are apollo client specific
