### ISSUE TITLE
persistCache not working in Internet Explorer 11

### ISSUE THREAD

**Issue by JustDoItSascha** [apollographql/apollo-cache-persist#91]
When I'm using persistCache on IE11 in combination with cache-and-network and I subscribe to a Query, the following is happening:

At first I get the data from the cache. In the background a request to the server is sent. The response comes with fresh data, but neither the Subscription is executed a second time nor the cache is updated.

It works on all other browsers, but not on IE. There is no error in the console. Has anyone an idea what is causing this error or is this a known bug?

```
persistCache({
       cache,
       storage: window.localStorage,
});
```

**Comment by wtrocki** [comment]
@JustDoItSascha IE11 is soo lagging behind with basic support of promises and other things that is really hard to expect it to work with modern libraries. 

You can resurrect to loading shims into the code and provide fallbacks.
If you have any input why this do not work and how we can adjust our solution to support it we will be gladly welcome, but we have no means to do investigation ourselves. 

IE will not work with async await. It will also require direct permission from user for local storage. 

https://caniuse.com/#search=async
